### ISSUE TITLE
Remove workarounds from `eth_chainservice_FEVM_test.go`

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1019]
Assuming the underlying issues are solved up stream, and a new version of wallaby (or other testnet) is deployed with those fixes, we should remove the following sections and have the test still pass without the workarounds:

https://github.com/statechannels/go-nitro/blob/eb199af1d4557631c4838829a2d9d03b2f629a1a/client/engine/chainservice/eth_chainservice_FEVM_test.go#L36-L40

https://github.com/statechannels/go-nitro/blob/eb199af1d4557631c4838829a2d9d03b2f629a1a/client/engine/chainservice/eth_chainservice_FEVM_test.go#L208-L228

This issue is effectively tracking the only remaining issues preventing us from being 100% compatible with FVM using unmodified code designed for Ethereum. The upstream issues are:

- https://github.com/filecoin-project/ref-fvm/issues/1182
- https://github.com/filecoin-project/ref-fvm/issues/1158

**Comment by lalexgap** [comment]
FYI Wallaby is currently down for maintenance but should be up around the 9th: https://filecoinproject.slack.com/archives/C03KGBTJ0BY/p1673033966147019?thread_ts=1673033767.579779&cid=C03KGBTJ0BY
