### ISSUE TITLE
Implement an API to query the store over RPC

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1020]
Currently the only way our client API communicates status information back to the caller is by sending  "events"(objectiveIds or vouchers) on one-way golang channels.  This means there's no way for an API caller to check the status of a channel(like after a reboot/crash). This also forces the caller of the API to be the one responsible for figuring out the current status by monitoring for events.

As part of [RFC 23](https://www.notion.so/statechannels/RFC-23-Overhaul-go-nitro-API-2c83cd05f59946ebb7354296de09f30e) I've put together a proposed query API and API proxies, that we've broadly discussed and agreed to implement.

There is still some ongoing discussion but here's roughly what it could look like:
```
type ChannelStatus string

const Proposed ChannelStatus = "Proposed"
const ReadyToFund ChannelStatus = "ReadyToFund"
const Closing ChannelStatus = "Closing"
const Complete ChannelStatus = "Complete"

type LedgerChannelInfo struct {
	ID      types.Destination
	Status  ChannelStatus
	Balance LedgerChannelBalance
}
type LedgerChannelBalance struct {
	AssetAddress  types.Address
	Hub           types.Address
	Client        types.Address
	HubBalance    *big.Int
	ClientBalance *big.Int
}


type PaymentChannelBalance struct {
	AssetAddress   types.Address
	Payee          types.Address
	Payer          types.Address
	PaidSoFar      *big.Int
	RemainingFunds *big.Int
}
type PaymentChannelInfo struct {
	ID      types.Destination
	Status  ChannelStatus
	Balance PaymentChannelBalance
}

type NitroQueryAPI interface {
	// GetPaymentChannelByReceiver returns the first payment found channel with the given receiver.
	// If no payment channel exists nil is returned.
	GetPaymentChannelByReceiver(receiver types.Address) PaymentChannelInfo
	// GetLedgerChannelByHub returns the first ledger channel found with the given hub.
	// If no ledger channel exists nil is returned.
	GetLedgerChannelByHub(Hub types.Address) LedgerChannelInfo
	// GetLedgerChannel returnns the ledger channel for the given id.
	// If no ledger channel exists nil is returned.
	GetLedgerChannel(id types.Destination) LedgerChannelInfo
	// GetPaymentChannel returnns the ledger channel for the given id.
	// If no ledger channel exists nil is returned.
	GetPaymentChannel(id types.Destination) PaymentChannelInfo
}
```

**Comment by geoknee** [comment]
Maybe the "proof of the pudding" for this feature is to change our integration tests to use this API instead of inspecting a (private) `store` object (to check things like total payments sent, channel status, objective status ...) ?

**Comment by geoknee** [comment]
This API needs also to be extended to the RPC server, too.
