### ISSUE TITLE
Objectives only get stored after crank which causes the query API to return no results

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1026]
While working on #1020 I introduced a simple query API that queries the store directly. However it looks like we only store the objective after it's  been cranked. This means you can call something like `CreateLedgerChannel` which returns a channel id, but until that crank is finished the query API will return no results for that channel id.

For example something like this fails in a simple test:
```
	response := alpha.CreateLedgerChannel(*beta.Address, 0, outcome)
	ledgerInfo, err := alpha.GetLedgerChannel(response.ChannelId)
```

However by adding a minimal delay it passes:
```
        response := alpha.CreateLedgerChannel(*beta.Address, 0, outcome)
	time.Sleep(1 * time.Millisecond)
	ledgerInfo, err := alpha.GetLedgerChannel(response.ChannelId)
```

## Possible Solutions
- Live with it. It doesn't take that long for the objective to be stored. However I could see this behavior being confusing/annoying for developers
- The client API doesn't return a channel id until the channel is already in the store when creating/updating channels. For example `CreateLedgerChannel` would block until the `engine` signals that the ledger channel is in the store.
- The query API blocks somehow until the channel is actually in the store?

**Comment by geoknee** [comment]
> The client API doesn't return a channel id until the channel is already in the store when creating/updating channels. For example CreateLedgerChannel would block until the engine signals that the ledger channel is in the store

I think the question here is, "Can the API consumer do anything useful with the channel id before the channel is in the store?" Clearly, they can't query the channel. This might be enough to justify having the API call block until the store is updated. 

Things I think we want for sure:
1. We want to document the behaviour well, whatever we decide it should be. 
2. We probably want _some way_ of having the consumer block until the channel is query-able. Whether that is a non-blocking API plus some event emitted later, or a one-time `chan` / promise-like solution, or simply having the API block as you describe above. 

I don't think your option 1 is good -- using `time.Sleep` seems like a massive antipattern. I also don't think option 3 is good -- it would be difficult for the engine to distinguish a channel which doesn't exist at all (mistyped channel id, for example) from a channel which has been created "in memory" but not committed to the store yet. So this seems to leave your option 2 as the best one.

**Comment by lalexgap** [comment]
@geoknee thanks for the input!

While I originally created this issue for querying a channel just after it's created, I think the same problem will apply to all mutation API calls. If you call `CloseVirtualChannel` and then `GetVirtualChannel`  immediately after you could get a status of `running` not `closing`.  This is due to how we designed our engine/client and my attempt to have the client query the store directly.  Since the client API requests are read in the main engine [run loop](https://github.com/statechannels/go-nitro/blob/1734d94d750dc95a26df3c04eb86e661a033c782/client/engine/engine.go#L138) it's possible that we're reading the store while the engine still has the API request in a queue.

I think a relatively easy solution is to expose a`ObjectiveStarted` chan in the engine that is used to notify the client API that an objective has been "started" (maybe the first time the engine cranks it? Or when we create it for the first time). Any mutation API on the client could block until the client receives a `ObjectiveStarted` event for the objective it's interested in. We could also investigate using a callback instead of chan.

Also of note is that we currently use unbuffered chans for clientAPI->engine [communication](https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/client/engine/engine.go#L93 . This means that an API call will block until the `engine` reads from the unbuffered chan. This means that client API calls are somewhat "blocking" as they will block until their request gets picked up by the engine.

**Comment by geoknee** [comment]
Here's my suggestion (I think similar to yours but slightly different):

We add a `handlerReturned chan` to the `ObjectiveRequest` object which the client sends to the engine:
https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/client/client.go#L162

Then, we can send on this `chan` / close it immediately after `handleObjectiveRequest` returns: 
https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/client/engine/engine.go#L139

The client can  pass that `chan` to the API consumer, so they can choose whether they want wait on the request having been handled / just fire and forget. 

I think these more focussed one-shot events might be nicer than re-using the general `e.toApi` `chan` -- we wouldn't need to filter / read events which may be irrelevant.

This pattern would also allow us to have the objective id computed asynchronously by the engine (rather than being computed by the client as it is now). I don't think we need that right now, but it's nice flexibility to have. 

What do you think?

**Comment by lalexgap** [comment]
> What do you think?

That's a good idea! I think the golang term for this pattern would be [futures](http://www.golangpatterns.info/concurrency/futures)
