### ISSUE TITLE
Consider storing deployment block number

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1041]
Instead of starting at the genesis block we should use the block the contract was deployed. I'm just not sure where to find that information.

_Originally posted by @lalexgap in https://github.com/statechannels/go-nitro/pull/1034#discussion_r1068554214_

**Comment by geoknee** [comment]
A couple of thoughts on this issue: 

1. We haven't yet tested out our polling system on a "mature" chain with many blocks. So the current state of the code _might_ cause a long delay asking for logs from old blocks which are irrelevant?
2. Would it make more sense to store something like `firstInitOfGoNitroClient`? Meaning, what if we scroll forward and the adjudicator deployment is also very far in the past compared to events that the wallet will care about. We could instead start asking for logs from the point where (i.e. a block just before) we first spun up a `Client` (or even a `chain service`).

**Comment by bitwiseguy** [comment]
@geoknee @lalexgap can this be closed since we are now updating and reading the `lastBlockNumSeen` in our store to determine how far to look back for missed chain events?

**Comment by geoknee** [comment]
Yes!
