### ISSUE TITLE
Rename "client" to "node"

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#1092]
With the introduction of rpc to go-nitro, the current [client terminology](https://github.com/statechannels/go-nitro/blob/79bae0c25cf4f522f265f112af50c99b6d57a355/client/client.go) is confusing. Instead, here is a rename proposal:
- The software that uses the rpc apis to make requests is called consumer or client.
- The software that monitors rpc apis and translates request to go-nitro framework calls is called node or server.

Concretely, this implies that the [client package](https://github.com/statechannels/go-nitro/blob/79bae0c25cf4f522f265f112af50c99b6d57a355/client/client.go#L2) and [client struct](https://github.com/statechannels/go-nitro/blob/79bae0c25cf4f522f265f112af50c99b6d57a355/client/client.go#L24) should be rename to api package and api struct.

**Comment by kerzhner** [comment]
I attempted to do this and noticed that the client terminology is sprinkled throughout go-nitro. So this rename would have broad implications (at least for the number of lines modified). Perhaps a smaller scope rename would be sufficient.

**Comment by geoknee** [comment]
> Concretely, this implies that the [client package](https://github.com/statechannels/go-nitro/blob/79bae0c25cf4f522f265f112af50c99b6d57a355/client/client.go#L2) and [client struct](https://github.com/statechannels/go-nitro/blob/79bae0c25cf4f522f265f112af50c99b6d57a355/client/client.go#L24) should be rename to api package and api struct.

I actually prefer `node` to api. in tests, we want to say we stand up a nitro node wrapped in an RPC server?

**Comment by geoknee** [comment]
We decided to go for `node` today in standup.
