### ISSUE TITLE
Strategy for uint64 transport

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#1093]
This card tracks the todo: https://github.com/statechannels/go-nitro/blob/79bae0c25cf4f522f265f112af50c99b6d57a355/client/rpc/client.go#L60

**Comment by geoknee** [comment]
I think `uint64(rand.Float64())` is going to return `0` every time, since the random float will be between zero and one and casting to an integer will take the integer part?

**Comment by geoknee** [comment]
Filed #1116
