### ISSUE TITLE
Nest `network` package under the `rpc` directory

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1095]
Could we nest `network` code be under the `rpc` directory? 

Longer term, if there is common / reused code between the rpc networking and the p2p networking, we could have a top level `network` package.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/1077#discussion_r1091909416_

**Comment by geoknee** [comment]
Not sure how this relates to #1091 (is it a duplicate?)

**Comment by kerzhner** [comment]
This issue is related to https://github.com/statechannels/go-nitro/issues/1091, but is not a duplicate.
