### ISSUE TITLE
Query Test flicker

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1101]
> 
> https://github.com/statechannels/go-nitro/actions/runs/4133299374/attempts/1
> 
> ```
> -test.shuffle 1675938555609154846
> --- FAIL: TestQueryPaymentChannel (0.04s)
>     helpers_test.go:176: Payment channel diff mismatch (-want +got):
>           query.PaymentChannelInfo{
>           	ID:      {0xde, 0xbc, 0xad, 0x20, ...},
>         - 	Status:  "Closing",
>         + 	Status:  "Complete",
>           	Balance: {Payee: {0xbb, 0xb6, 0x76, 0xf9, ...}, Payer: {0xaa, 0xa6, 0x62, 0x8e, ...}, PaidSoFar: &{abs: {1}}, RemainingFunds: &{abs: {1}}},
>           }
> FAIL
> FAIL	github.com/statechannels/go-nitro/client_test	6.511s
> ```

**Comment by geoknee** [comment]
See https://github.com/statechannels/go-nitro/actions/runs/4102722117/jobs/7076064279

**Comment by geoknee** [comment]
And https://github.com/statechannels/go-nitro/actions/runs/4102722117/jobs/7076029794 (seems like a different problem).

Not clear this is RPC related or not.

**Comment by geoknee** [comment]
Could be a different issue, but we are still seeing flickers: 

https://github.com/statechannels/go-nitro/actions/runs/4133299374/attempts/1

```
-test.shuffle 1675938555609154846
--- FAIL: TestQueryPaymentChannel (0.04s)
    helpers_test.go:176: Payment channel diff mismatch (-want +got):
          query.PaymentChannelInfo{
          	ID:      {0xde, 0xbc, 0xad, 0x20, ...},
        - 	Status:  "Closing",
        + 	Status:  "Complete",
          	Balance: {Payee: {0xbb, 0xb6, 0x76, 0xf9, ...}, Payer: {0xaa, 0xa6, 0x62, 0x8e, ...}, PaidSoFar: &{abs: {1}}, RemainingFunds: &{abs: {1}}},
          }
FAIL
FAIL	github.com/statechannels/go-nitro/client_test	6.511s
```

**Comment by lalexgap** [comment]
> Could be a different issue, but we are still seeing flickers:
> 
> https://github.com/statechannels/go-nitro/actions/runs/4133299374/attempts/1
> 
> ```
> -test.shuffle 1675938555609154846
> --- FAIL: TestQueryPaymentChannel (0.04s)
>     helpers_test.go:176: Payment channel diff mismatch (-want +got):
>           query.PaymentChannelInfo{
>           	ID:      {0xde, 0xbc, 0xad, 0x20, ...},
>         - 	Status:  "Closing",
>         + 	Status:  "Complete",
>           	Balance: {Payee: {0xbb, 0xb6, 0x76, 0xf9, ...}, Payer: {0xaa, 0xa6, 0x62, 0x8e, ...}, PaidSoFar: &{abs: {1}}, RemainingFunds: &{abs: {1}}},
>           }
> FAIL
> FAIL	github.com/statechannels/go-nitro/client_test	6.511s
> ```

This looks like an issue related to the query tests and unrelated to RPC.
