### ISSUE TITLE
Serialized json in logs

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#1106]
We see log lines like: `{"client":"irene","rpc":"","scope":"","t":1675720316,"m":"{\"l\":\"panic\",\"engine\":\"0x111A00\",\"error\":\"error populating channel data for objective VirtualDefund-0xdb16e08abfa1efa15d1690f1f92736d118c6b7eee60c76fe27d071e76a870ac2: error retrieving left ledger channel data for objective VirtualDefund-0xdb16e08abfa1efa15d1690f1f92736d118c6b7eee60c76fe27d071e76a870ac2: store: failed to find required channel data\",\"t\":1675720316,\"caller\":\"engine.go:152\",\"m\":\"0x111A00868581f73AB42FEEF67D235Ca09ca1E8db, error in run loop\"}"}`

Logs should not contain serialized json.

**Comment by lalexgap** [comment]
This should be fixed by #1112
