### ISSUE TITLE
Add nonce reuse  protection

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1116]
Nonce reuse is dangerous and opens up replay attacks. See https://docs.statechannels.org/protocol-tutorial/0010-states-channels/#channelnonce .

We currently use random nonces, which in theory makes reuse of a nonce very unlikely. However, we could change to use a different strategy, or make a programming error which results in incoming requests which reuse nonces. 

We could:

*  enhance the `store` to keep track of all channelids used so far, and throw an error if we ever encounter a collision. 
This would mean storing 32 * num_channels_ever_opened_with_same_fixedpart bytes in the store. If that ever became an issue, we can make a way for the user to rotate their channel key and delete that list. OR

* bring the random nonce generation "in house" and reduce the risk of having it messed up by the RPC client.

**Comment by lalexgap** [comment]
I think we have done 
>ring the random nonce generation "in house" and reduce the risk of having it messed up by the RPC client.

as we [now choose a random nonce in the node](https://github.com/statechannels/go-nitro/blob/25f50f2ec21fbaf182ee3afb2ebaa086cb5c89b4/node/node.go#L222)
