### ISSUE TITLE
Re run tests against hyperspace v1 endpoint

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1118]
Messages coming over slack suggest:

1. Hyperspace network would like folks to try out their websockets endpoint (https://filecoinproject.slack.com/archives/C017HM9BJ8Z/p1675931276421509) 
2. Querying logs before a recent upgrade is _not supported_. We might find something similar on Filecoin mainnet so may need a workaround (we may not be able to query from the genesis block). (https://filecoinproject.slack.com/archives/C04JEJB82RY/p1675342525871519)

Also recent manual testing suggests our tests do not pass against hyperspace. So there are several questions to answer.

**Comment by lalexgap** [comment]
> Messages coming over slack suggest:
> 
>     1. Hyperspace network would like folks to try out their websockets endpoint (https://filecoinproject.slack.com/archives/C017HM9BJ8Z/p1675931276421509)

The endpoint in that slack message is `https://wss.node.glif.io/` which seems to be an https endpoint of some kind. I'm not sure what the correct websocket address is but I tried using both `https://wss.node.glif.io/` and `wss://wss.node.glif.io/` with no success.

Using the websocket endpoint from this [post](https://filecoinproject.slack.com/archives/C04JEJB82RY/p1674138221210029?thread_ts=1674130269.290119&cid=C04JEJB82RY) **did work**.
