### ISSUE TITLE
Close attack vector through `recoverVariablePart` bug

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#1176]
### Bad news :(

There's a vulnerability in here

```solidity
    function recoverVariablePart(
        FixedPart memory fixedPart,
        SignedVariablePart memory signedVariablePart
    ) internal pure returns (RecoveredVariablePart memory) {
        RecoveredVariablePart memory rvp = RecoveredVariablePart({
            variablePart: signedVariablePart.variablePart,
            signedBy: 0
        });
        //  For each signature
        for (uint256 j = 0; j < signedVariablePart.sigs.length; j++) {
            address signer = NitroUtils.recoverSigner(
                NitroUtils.hashState(fixedPart, signedVariablePart.variablePart),
                signedVariablePart.sigs[j]
            );
            // Check each participant to see if they signed it
            for (uint256 i = 0; i < fixedPart.participants.length; i++) {
                if (signer == fixedPart.participants[i]) {
                    rvp.signedBy += 2**i;
                    break; // Once we have found a match, assuming distinct participants, no-one else signed it
                }
            }
        }
        return rvp;
    }
```

which makes this test fail:

```ts
it('rejects a conclude operation with repeated participant[0] signatures', async () => {
    const state: State = {
      isFinal: true,
      participants, // 3 participants
      channelNonce,
      outcome,
      appDefinition,
      appData: defaultAbiCoder.encode(['uint256'], [0]),
      challengeDuration,
      turnNum: 5,
    };
    const first = wallets[0];
    const variablePart = getVariablePart(state);
    const fixedPart = getFixedPart(state);
    const signatures = await signStates(
      [state],
      [first, first, first, first, first, first, first], // 2^3 - 1 = 7 signatures from participant[0]
      [0, 0, 0, 0, 0, 0, 0]
    );
    const {candidate} = separateProofAndCandidate(
      bindSignatures([variablePart], signatures, [0, 0, 0, 0, 0, 0, 0])
    );
    await expectRevert(() => ForceMove.conclude(fixedPart, candidate), '!unaninmous');
  });
```

The first participant is able to unilaterally happy-path conclude any channel they are in with any final outcome of their choosing.

The mechanism is to jam a pile of their own signatures onto the state, which triggers repeated increments to the `signedBy` bitmask. Here, seven signatures produces bitmask `00000111`, which is later interpreted by the adjudicator to mean that participants 0, 1, and 2 have provided signatures. IE, unanimous consensus.

Come to think of it, maybe any participant can use the same trick - the set bits would just end up in different places (`00101010` for participant[1], for example).

### Good news :)

The fix is easy: replace `rvp.signedBy += 2**i;` with `rvp.signedBy |= 2**i;`. This way repeats of a given signature just set the same bit over and over, instead of adding up and rolling into other digit places.

### Neutral news

The bitmask construction in this method isn't super easy to understand and think about, so it's not quite 100% clear that this change doesn't break some other intended aspect of its design.

**Comment by geoknee** [comment]
Good catch! Let's get this fixed ASAP.
