### ISSUE TITLE
Testground stalls out trying to delete container

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1187]
An [example](https://github.com/statechannels/go-nitro/actions/runs/4505561078/jobs/7931422365?pr=1158)

If we look at the [logs](http://34.168.92.245:8042/logs?task_id=cgecjionr2gjmltl49u0) we see an error when trying to delete a container.
```
Mar 23 22:01:07.896837	[31mERROR[0m	failed while deleting container	{"runner": "local:docker", "run_id": "cgecjionr2gjmltl49u0", "error": "Error: No such container: 3cf50828a6eac77f0804fa75dab52c35aaa9016188a35c25bd48833e3a14f3b2"}
```

The testground task stills seems to be running 25 minutes later, so it looks like this essentially causes testground to stall out and become unusable

**Comment by geoknee** [comment]
We're not currently running testground.
