### ISSUE TITLE
Create a production constructor

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1205]
I think a production constructor is very important and it would really help clarify all of this. 

The lack of the existence of such a constructor had me reading the test files as "the only way" we do things at the moment. I take your point that in the wild we wouldn't do it that way.

As discussed during standup -- the production constructor could read from a config file, plus read sensitive information (private key) from the command line.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/issues/1201#issuecomment-1492315623_

**Comment by NiloCK** [comment]
Production constructor should:

- succeed, with warnings, when networking services fail to initialize. IE, as a durable service, nitro should be runnable offline or with flaky connectivity.

Nitro client does not currently have any general purpose status reporting, which are probably a prerequisite.

**Comment by geoknee** [comment]
We could take some inspiration from here https://geth.ethereum.org/docs/fundamentals/config-files

**Comment by geoknee** [comment]
And here https://github.com/avelino/awesome-go#configuration
