### ISSUE TITLE
Ledger defund completes before virtual defund

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#1216]
Virtual channel defunding includes finalizing the virtual channel and removing guarantees that fund the virtual channel from ledger channels. In the current go-nitro implementation, it is possible for the following scenario to occur:
1. Virtual defunding is initiated and all parties sign the final state.
2. Proposals for ledger channel guarantee removal are sent around.
3. When a participant has all proposals that the participant needs, the participant considers virtual defunding completed.
4. The participant can now initiate ledger direct defunding.
5. The counterparty in the ledger channel happily participates in ledger defunding even when its virtual defunding objective has not completed. It is possible to start (and even finish) ledger defunding before a virtual defund objective completes.

This brings up open questions:
1. Is there value in multiple objectives running for a single channel? If the answer is no, then it will be possible for objectives to be rejected due to other running objectives.
2. Do we need other guardrails for the types of objectives/states a go-nitro client accepts? As a note, there exists a [policymaker](https://github.com/statechannels/go-nitro/blob/e75d30833fead299085b0fcc39060baa310baa8c/client/engine/policy_maker.go#L15).
3. If multiple objectives for a channel can run simultaneously, should the objectives be aware of each other? More concretely, how does a ledger defund objective block until the virtual defund objective has completed?

Attached is a trimmed log file from [a failing CI unit test](https://github.com/statechannels/go-nitro/actions/runs/4694988561/attempts/1) that exposed this issues: [trimmed.log](https://github.com/statechannels/go-nitro/files/11256356/trimmed.log)

**Comment by lalexgap** [comment]
> This brings up open questions:
> 
>  1. Is there value in multiple objectives running for a single channel? If the answer is no, then it will be possible for objectives to be rejected due to other running objectives.

I think our stores already implement the idea of an [objective owning a channel](https://github.com/statechannels/go-nitro/blob/1d2d74a89b9c45fad65b81f94a989fee56aec4a4/client/engine/store/memstore.go#L110), which means we should never have multiple active objectives for a channel.

> * The counterparty in the ledger channel happily participates in ledger defunding even when its virtual defunding objective has not completed. It is possible to start (and even finish) ledger defunding before a virtual defund objective completes.

I'm actually surprised the counterparty didn't `panic` due to the the `store` logic mentioned above.

**Comment by lalexgap** [comment]
I'm also slightly surprised we're seeing this because the failing integration test is [explicitly waiting for all virtual defund objectives](https://github.com/statechannels/go-nitro/blob/1d2d74a89b9c45fad65b81f94a989fee56aec4a4/client_test/integration_test.go#L187-L188) to complete on **all** clients.

The test shouldn't try direct-defunding until all clients have reported the virtual defund objectives as complete. Perhaps the check is faulty?

**Comment by kerzhner** [comment]
The following thoughts are per discussion with @lalexgap. We have a problem with integration tests (discussed above). After we fix the problem, all nodes will wait for all virtual defund objective completions before starting direct defunding. So this issue will no longer manifest in integration tests.

However, this issue will still exist. One possible resolution is a short term fix with a long term extension. The short term fix is for a nitro node to reject direct defund objectives for a ledger channel that has virtual fund/defund objectives. The long term extension is more sophisticated:
- We might want to "lock" a ledger channel once a ledger channel defund is requested. This means that all proposals should complete or fail and no new proposal are accepted. After that a channel is defunded.
- We might want to implement an objective retry mechanism if an objective is rejected by another node.

**Comment by geoknee** [comment]
> We might want to "lock" a ledger channel once a ledger channel defund is requested. This means that all proposals should complete or fail and no new proposal are accepted. After that a channel is defunded.

@lalexgap and I discussed this today, this seems like a good approach and should replace this line in the engine:

https://github.com/statechannels/go-nitro/blob/e062f38a13a01d74d3abb3417b75369c59fd727c/client/engine/engine.go#L229

**Comment by geoknee** [comment]
Looks like I hit this issue again here https://github.com/statechannels/go-nitro/actions/runs/4746124808/jobs/8429354025?pr=1222 .

**Comment by geoknee** [comment]
> Looks like I hit this issue again here https://github.com/statechannels/go-nitro/actions/runs/4746124808/jobs/8429354025?pr=1222 . [integration-test-logs.zip](https://github.com/statechannels/go-nitro/files/11284797/integration-test-logs.zip)

As discussed today, this looks like a different issue. Possibly redundant messages causing a crank after an objective has completed.
