### ISSUE TITLE
Write specs for how a Myel node can write a "voucher manager" system

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#122]
To enable Myel (or other teams) to prototype Nitro payments in their app, we can provide a spec/API for them to use, pretending that they have a funded channel.

- [x] #130 
- [x] #137
- [x] Write a [markdown](https://www.notion.so/statechannels/Voucher-channels-f8609ab3f45142eda3e552e58a676bb1) explaining the lifecycle of an app channel
- [ ] Write prototype code that "makes payments" in an app channel (eg. like [here](https://github.com/statechannels/go-nitro/blob/784242d9697dde6296cb298b4feb6a46b5b4f4f8/channel/state/app-channels.go))

**Comment by geoknee** [comment]
@andrewgordstewart what's the status of this work?

**Comment by andrewgordstewart** [comment]
I've held off on the last item, as we ought to discuss who should work on this project with PL on Friday.

**Comment by geoknee** [comment]
Let's make that last item a new issue and assign it to the current sprint?

**Comment by andrewgordstewart** [comment]
We can come back to the last item when it makes sense!
