### ISSUE TITLE
write a MemoryStore

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#128]
This is necessary for the engine to actually do stuff! Therefore it is a blocker to writing integration tests with engines.

Related to #78. 

https://www.notion.so/statechannels/Protocol-interface-e076fe46c0774122818d1abb7cfd0c5a#c4a5bd2e54d84d218c8a0cf889305dae

The interface to the store may or may not need to change.

**Comment by NiloCK** [comment]
closed via #149
