### ISSUE TITLE
Support 0-hop virtual channels

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1296]
This gives us a very quick route to allowing payments between client and server with no intermediary required.

It has advantages and disadvantages over implementing direct payment channels (TODO fill out on this issue)

**Comment by NiloCK** [comment]
Context:

go-nitro has been developed with virtually funded channels as the presumed "payments" layer. Consequently, the underlying layer of directly funded ledger channels (`consensus_channel`) have no API for direct value exchange.

IE, there is no functionality to
- directly update a ledger channel's outcome from `{alice: 2, bob: 3, ... (guarantees)}` to `{alice: 1, bob: 4, ...(guarantees)}`
- sign this update
- send the update

Ledger channels are capable of doing this operation, but in context of an active ledger channel any implementation will be non-trivial. In-progress virtual-fund or vitrual-defund objectives rely on predictable transitions of ledger state from the pre to post objective states. These predictable transitions are enforced by queuing proposals and processing in order. A "directpay" operation operating on the ledger channel would likely be subject to the same queue, but the existing implementations of this queue is specific to virtual fund or virtual defund proposals.

Instead, payments between ledger channel participants can be more easily realized by running the existing virtual-fund operation with the two ledger channel participants as the only participants.

**Comment by NiloCK** [comment]
closed by #1315
