### ISSUE TITLE
Stale MDNS records can cause test flickers

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1338]
# Problem 
> That change doesn't resolve the issue with `go test ./client_test -run TestStartStop -v -count=10` (without running the race condition checker) (for me, at least).

I'm not sure which issue you're seeing but I'm still able to reproduce a error like this occasionally  
```
level":"warn","message-service":"0x111A00","time":1686170132684,"caller":"service.go:236","message":"Failed to add peer 16Uiu2HAmEKETsG9XtxdXpyYNxKfkuBdWEDq656zrWZZd5FvVvtZ1 with address /ip4/127.0.0.1/tcp/3007 with error: failed to dial 16Uiu2HAmEKETsG9XtxdXpyYNxKfkuBdWEDq656zrWZZd5FvVvtZ1:\n  * [/ip4/127.0.0.1/tcp/3007] failed to negotiate security protocol: read tcp4 127.0.0.1:3005->127.0.0.1:3007: read: connection reset by peer"}
```

I think we might be running into an  `mdns` issue. An important thing to note about mdns is that it's handled by your local machine ( like [apple bonjour](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/NetServices/Introduction.html),  so changes can persist between test runs. Libp2p peer discovery just makes use of this by publishing and querying your local `mdns`.  You can actually see what's happening by running the command `dns-sd -B _p2p._udp` ; you can see libp2p adding and removing `mdns` entries. 

When we star a test run and construct a message service, libp2p will announce itself and query the local `mdns` network. I think if we get unlucky with timing (or maybe there's caching involved?) when libp2p queries mdns it could get back mdns entries from older test runs that have yet to be removed. These entries are always going to point to the same multiaddress/url so even if they're old they're not wrong.
```
 dnsaddr=/ip4/127.0.0.1/tcp/3007/p2p/16Uiu2HAmEKETsG9XtxdXpyYNxKfkuBdWEDq656zrWZZd5FvVvtZ1
14:56:48.715  0og7dn5pxb96a75hlpzosv9shuv9sfayo2twknxwcg._p2p._udp.local. can be reached at 0og7dn5pxb96a75hlpzosv9shuv9sfayo2twknxwcg.local.:4001 (interface 12)
 dnsaddr=/ip4/127.0.0.1/tcp/3007/p2p/16Uiu2HAmEKETsG9XtxdXpyYNxKfkuBdWEDq656zrWZZd5FvVvtZ1
```

However if we get unlucky with timing we could attempt to connect to a peer message service that hasn't started yet based on `HandlePeerFound` being triggered by a stale/cached mdns entry.

It does like the mdns entries added by libp2p to get removed (seen by running `dns-sd -B _p2p._udp`) but there does seem like a delay before they are removed. That might explain why we don't run into this all the time, we have to get unlucky with timing (I run `go test ./client_test -run TestStartStop  -count=1000 --shuffle=on -timeout=1m` to catch it).

# Solutions
If that's what's happening we can try to do some hardening to `HandlePeerFound` so it handles this situation more gracefully and doesn't blow up. However my first view attempts at that became pretty complicated and involved.

Another option may be to manually flush the mdns before running a test. (I know you can do that on the mac by running `sudo killall -HUP mDNSResponder`)

Or we could just create an issue and monitor this. We know `mdns` isn't production ready so we're going to have to replace it eventually anyways. I'm only able to reproduce this by running `TestStartStop` with a large count value to hammer my local mdns. It doesn't seem to happen often on CI/regular test runs 🤞

_Originally posted by @lalexgap in https://github.com/statechannels/go-nitro/issues/1327#issuecomment-1581670735_

**Comment by geoknee** [comment]
We're not going to fix this right now since MDNS will be replaced soon.

**Comment by geoknee** [comment]
I'm also not convinced the problems I am seeing are mdns related.

**Comment by geoknee** [comment]
Useful app with GUI https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12

**Comment by kerzhner** [comment]
[This CI failure](https://github.com/statechannels/go-nitro/actions/runs/5512590582/jobs/10049620450) of `TestRpcWithNats` test could be related to this issue:

```
panic: failed to dial 16Uiu2HAmAowhhPoBqzAHDku9VgUyLwpuRuiPNgSRecikRdpy6ERg:
  * [/ip4/127.0.0.1/tcp/3108] failed to negotiate stream multiplexer: read tcp4 127.0.0.1:3105->127.0.0.1:3108: read: connection reset by peer
 ```

**Comment by bitwiseguy** [comment]
Closing since mDNS has been removed from codebase
