### ISSUE TITLE
Rename `LedgerChannelInfo` struct fields

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#1362]
These calls to a go rpc client:

```
bobL := bobClient.GetLedgerChannel(bobLedger.ChannelId)
t.Log("Bob", bob.Address())
t.Log("BobLClient", bobL.Balance.Client)
t.Log("BobLHub", bobL.Balance.Hub)
```

Result in the following output:

```
rpc_test.go:182: Bob 0x6813Eb9362372EEF6200f3b1dbC3f819671cBA69
rpc_test.go:183: BobLClient 0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF
rpc_test.go:184: BobLHub 0x6813Eb9362372EEF6200f3b1dbC3f819671cBA69
```

(Bob is not the hub in this scenario).

`Hub` `Client` seem to be referring here to `Follower` `Leader`, which are a consequence of which participant initiated the channel.

**Comment by geoknee** [comment]
Do `Hub` and `Client` really make sense for multihop situations? I think we need to change this data structure:

https://github.com/statechannels/go-nitro/blob/3cb69815a77fe6daac09ac1d02bedb7c4d6b882e/client/query/types.go#L41-L48
