### ISSUE TITLE
Implement a MockChain, attach to MockChainService

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#142]
Current MockChainService implementation has a broadcasting / engine-engine-communication problem.

- if there is only one `mockchainservice`, then engines are competing to read event written to the service's `Out()` channel
- if there are `mockchainservice`s per engine, then it's not clear how messages get from engine A to engine B

Current plan is to:
- implement a singleton style MockChain, which collects `tx`s from `MockChainService`s, and emits events to them
- attach each engine's `MockChainService` to it

From: _Originally posted by @NiloCK in https://github.com/statechannels/go-nitro/pull/139#discussion_r784079867_

**Comment by geoknee** [comment]
via #155
