### ISSUE TITLE
Add a `reverse-proxy-http-server` cmd

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1482]
This would be akin to nginx. An http server which accepts http requests that have nitro-style payment headers in them. 

The server will talk to a nitro node over rpc to validate the payment. It checks if the payment is sufficient and if so forwards the request to a delegated server (such as `booster-http`). 

A "sufficient payment" can be:
* V0: any nonzero payment
* V1: a payment covering some `/pricing/` endpoint of the delegated server. It might just be a $/KB exchange rate. 

It's a bit awkward to resolve the payment with the size of the file. Which component owns pricing? Is there a performant system for having the proxy do payments without also having lots of information about the data. 

### Design documentation
We would like some nice diagrams to show what is going on. 

### Testing
We would want to mock out boost / replace it with a very simple http server (`nitro-protocol.pdf`). We would to make sure no-one can access the "delegated server" directly, only through the proxy.

**Comment by lalexgap** [comment]
Done by #1483
