### ISSUE TITLE
The eth chain service should query for historic logs

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1500]
Right now the eth chain service calls [SubscribeFilterLogs](https://github.com/statechannels/go-nitro/blob/7cc2c812388313a57b996e9341cb6ae2ee535621/node/engine/chainservice/eth_chainservice.go#L292) to get contract events.  However [SubscribeFilterLogs](https://github.com/ethereum/go-ethereum/issues/15063) only supports new events; it doesn't return any historic events that have happened.

That means if a nitro node misses a contract event (due to being offline) it will never catch up on that event, stalling out the directfund protocol. 

Instead the chain service should fetch historic logs by calling `[FilterLogs](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client.FilterLogs)` on start up.

**Comment by lalexgap** [comment]
I think there may also be a related issue that we can run into testing against long-lived contracts on a testnet. If we delete a node's local store after it has made a bunch of deposits on chain (like we often do in testing) then we run into an error when it tries to deposit later.  This is because we never attempt to look up any existing deposits, so s we pass in `expectedHeld=0` which [fails](https://github.com/statechannels/go-nitro/blob/7cc2c812388313a57b996e9341cb6ae2ee535621/nitro-protocol/contracts/MultiAssetHolder.sol#L50) since the adjudicator has deposits from the node(before it wiped it's store).

Unfortunately this will take a little more work to solve since chain events are only [handled by objectives](https://github.com/statechannels/go-nitro/blob/7cc2c812388313a57b996e9341cb6ae2ee535621/node/engine/engine.go#L434). So in the case of a fresh store, even if we fetch the historic events and replay them, there will be no objectives in the store to listen to them. To resolve this we could update the engine so it queries for the current adjudicator balance and pass that in when [constructing a new direct fund objective.](https://github.com/statechannels/go-nitro/blob/7cc2c812388313a57b996e9341cb6ae2ee535621/protocols/directfund/directfund.go#L60).

**Comment by bitwiseguy** [comment]
Completed in https://github.com/statechannels/go-nitro/pull/1765
