### ISSUE TITLE
Flicker in  TypeScript RPC Client Test

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1552]
https://github.com/statechannels/go-nitro/actions/runs/5892480976/job/15981850858

1. We should fix the flicker, probably by increasing the appropriate timeout.
2. It was hard to understand what caused the failure, so we should look into improving how we manage the output of the background process better. 

An alternative would be to consider a more lightweight way to test the rpc client against the rpc server.

**Comment by lalexgap** [comment]
> 2\. It was hard to understand what caused the failure, so we should look into improving how we manage the output of the background process better.

I took a brief[ look into this](https://github.com/statechannels/go-nitro/pull/1555) and wasn't able to get anything working. I'm not sure if it's worth too much effort since most times understanding the failure will require looking at the logs anyways.

**Comment by geoknee** [comment]
https://github.com/statechannels/go-nitro/actions/runs/5938118888/job/16101892887?pr=1575

**Comment by lalexgap** [comment]
> https://github.com/statechannels/go-nitro/actions/runs/5938118888/job/16101892887?pr=1575

@geoknee took a quick peek at the logs from this failure and I'm seeing this error:
```
    Block Time: "Tue, 22 Aug 2023 11:27:00 +0000"

[36m# github.com/quic-go/quic-go/internal/qtls
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
[0m
    Bloc
```
This is the error we saw when using a [pre-v0.30 version of libp2p with go 1.21](https://github.com/statechannels/go-nitro/issues/1526). Any change this branch was stale and using an older version of libp2p somehow?
