### ISSUE TITLE
RPC test flicker

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1613]
https://github.com/statechannels/go-nitro/actions/runs/6022825161/attempts/1?pr=1612

**Comment by geoknee** [comment]
3+ failures on this PR https://github.com/statechannels/go-nitro/actions/runs/6022579203?pr=1602

**Comment by NiloCK** [comment]
This test seems flaky everywhere. Some recent ones:
- https://github.com/statechannels/go-nitro/pull/1612 (comment only change)
- https://github.com/statechannels/go-nitro/pull/1575 (edits to unrelated .yml workflows)

**Comment by geoknee** [comment]
From standup today: 

* suspect that the constrained resources of the CI environment may be a factor
* could try swapping anvil out for ganache or some alternative
* could try verbose logging from anvil
* could try writing a test which covers the same code but doesn't require setting up an external chain
    - left field idea: generate a request string with the Go and TS rpc clients. Check they are equal. 
* but we do we want something hitting an external chain. Could use circleCI or some other environment to run that.

**Comment by bitwiseguy** [comment]
This turned out to be an issue with the `foundry`/`anvil` nightly build that is used by our CI. Foundry seems to have fixed thi issues in [this PR](https://github.com/foundry-rs/foundry/pull/5759), and our CI is now reliably passing.
