### ISSUE TITLE
Deploy payment client to netlify

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1666]
Take our payment client UI react app and deploy it publicly.

**Comment by lalexgap** [comment]
@geoknee do you have experience with netlify from the nitro gui days?

**Comment by geoknee** [comment]
Yes, site is deployed to https://nitro-payment-demo.netlify.app/ 

For now it builds / deploys automatically from the `fildev-payment-client` branch.

**Comment by lalexgap** [comment]
@geoknee it looks like only the initial deployment occurred: https://app.netlify.com/sites/nitro-payment-demo/deploys?filter=fildev-payment-client

Is there something we have to do to trigger the deploy again?

**Comment by geoknee** [comment]
Looks like there were some more deploys recently -- did you already update some settings?

In my understanding, it will redeploy when we push to that branch.

**Comment by lalexgap** [comment]
@geoknee  Yup, I [ended up updating `netlify.toml` ](https://github.com/statechannels/go-nitro/pull/1672/commits/670e817c1b5de5b7c6f3cbafbd07e69fc587bc28) so that it will deploy when the payment client or rpc client packages are updated.
