### ISSUE TITLE
Identify / Get buy in from a  Storage Provider

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1669]
We can reach out directly in the appropriate slack channels?
We could ask our contacts for help identifying Storage Providers:
* Patrick Woodhead
* Hannah Howard
* Rest of boost team
* Sarah Thiam

We could try and remember the friendly / enthusiastic SP. who was a judge / advisor for one of our FVM cohort things...

Failovers are:
* run our own testnet SP
* use a basic http-server

**Comment by lalexgap** [comment]
We should also consider what files the storage providers are currently serving.  If a storage provider is mostly storing archival data it might make the demo slightly awkward.

**Comment by lalexgap** [comment]
We could consider paying a storage provider to host something small(nitro white paper, nitro logo, etc..) and use that as the demo file. Might be a bunch of hoops to jump through and it would cost money though...

**Comment by lalexgap** [comment]
Also worth considering that if we want to use "micropayments" the storage provider would have to support HTTP Range requests. A lot of http server frameworks have this built in so storage providers may already support it.

**Comment by geoknee** [comment]
This is probably a good place to find active retrieval providers https://overall.filecoin-goldenretriever.io/

**Comment by geoknee** [comment]
Have reached out to the bedrock team via slack to see if they can connect us with the right people.
