### ISSUE TITLE
Create demo UI mock up

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1686]
Put together a simple mockup of how we want the demo to look and flow.  #1677 captures some UI ideas which can be incorporated.

**Comment by geoknee** [comment]
We want to display balances in FIL, not wei/ETH.

**Comment by geoknee** [comment]
This is still a work in progress. But functionally, we are expecting:
* to not display the channel id in the UI
* not have a text box for proxy URL (this should be hardcoded)
* reinstate a button to mess up the payment / not do the payment
* "Fetch" should be "Pay and download"
* add some file metadata and perhaps a big file icon
    - cost per byte
    - file size
    - total cost
* retain mobile friendliness
* possibly fetch a different file by clicking the fetch button again (random selection out of a set of 10)
*

**Comment by geoknee** [comment]
https://www.figma.com/file/xxNNhTsWfxXJKft1r0105F/FileHammer?type=design&node-id=247-43&mode=design&t=MyOFqnmrMnVU5dT3-0
