### ISSUE TITLE
Allow cheaper pricing of data

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1718]
Due to our implementation of `COST_PER_BYTE` the lowest amount we can charge is `1 wei` per a byte. This means large files are expensive.

We could change it to `COST_PER_KILOBYTE`. Or allow a fraction or decimal value.

**Comment by geoknee** [comment]
I think it's not so important how "expensive" the files are, given that we are using worthless test money anyway. What's more important for the demo is that we don't run out of funds (given we aren't allowing the flows to deposit more / defund channels / rebalance etc). We can probably solve that problem by ensuring channels are funded with enough test money?

**Comment by geoknee** [comment]
Suggested numbers here https://www.notion.so/statechannels/TODOs-Targets-42d9dc90f62c4148abaf9a0444cc054b?pvs=4#0b1b2e71708f4070a59ad2d48a2986c7
