### ISSUE TITLE
Update cloud nodes to use archive node

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#1726]
Filecoin has provided us with an archive node we can use.

We just need to update our workflows to set the jwt token from a github secret.

**Comment by bitwiseguy** [comment]
Will need to edit root level `main.go` to accept JWT_TOKEN as an environment variable if you want to follow the same pattern as `CHAIN_PK`. See this line for reference: https://github.com/statechannels/go-nitro/blob/main/main.go#L115

**Comment by geoknee** [comment]
We would like to run some manual tests first:
- [ ] Point our local integration test against the laconic endpoint
- [ ] Point "" against the glif archive endpoint
- [ ] if successful, deploy the necessary change to the cloud

**Comment by geoknee** [comment]
"local integration test" here means running these instructions https://www.notion.so/statechannels/Running-the-demo-locally-eb93414f3b0747b7821ccd663ab7f8e2 but with modified `alice.toml, ...` files .

**Comment by geoknee** [comment]
#1737

**Comment by bitwiseguy** [comment]
I got the following error when using the archive node provide by glif:
```
{"time":"2023-09-18T20:26:33.889498994Z","level":"INFO","msg":"Connected to ethclient","url":"wss://calibration.node.glif.io/archive/lotus/rpc/v1"}
{"time":"2023-09-18T20:26:34.073562252Z","level":"INFO","msg":"Found chain id","chainId":314159}
{"time":"2023-09-18T20:26:34.641772992Z","level":"INFO","msg":"checking for missed chain events","address":"0x6cf836B2A139e04FF05A0E8faA47b5731E331d48","startBlock":5,"currentBlock":924746}
{"time":"2023-09-18T20:26:34.831257531Z","level":"ERROR","msg":"failed to retrieve old chain logs. invalid epoch range: range between to and from blocks is too large (maximum: 60480)","address":"0x6cf836B2A139e04FF05A0E8faA47b5731E331d48"}
```
We could probably get around this error if we broke the `ecs.chain.FilterLogs` query into 60480 block chunks and made multiple requests until we reached the current block

**Comment by bitwiseguy** [comment]
The `laconic` indexed endpoint does not appear to support websockets. We might be able to use it for the initial `ecs.checkMissedEvents` call and then use a different RPC provider for the websocket event subscriptions. That would require some refactoring of the `chainservice` because right now it expects to use a single RPC provider endpoint for the old events query and the new event subscriptions.

**Comment by bitwiseguy** [comment]
RPC provider constraint summary:
* Laconic: single request max epochs = 60480
* Glif: single request max epochs = 60480
* Infura: [constraints](https://docs.infura.io/networks/ethereum/json-rpc-methods/eth_getlogs#constraints)
