### ISSUE TITLE
Browser caching leads to surprising behaviour when "skip payment" is selected

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1739]
If a file has already been downloaded, the browser will not bother requesting it again. If the user has selected "skip payment" we want there to be a 402 error. 

We should look into whether it is possible to prevent this caching behaviour. 

Or, if we use a different file each time that may be enough of a get around.

**Comment by lalexgap** [comment]
This only seems to happen in `chrome` but it's pretty easy to reproduce.
