### ISSUE TITLE
Enforce / Encourage consistent casing for variables, filenames, packages and directories across the repository

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#174]
Related to #163, #156 and https://github.com/statechannels/go-nitro/pull/156#issuecomment-1016269977. 

We should stick with established conventions (where they exist) unless a good reason exists to depart from that. 

We should enforce the convention via `golangci-lint` if possible which we already use in our continuous integration github action. 

We should tell developers how to stick to convention (ideally, their editor or pre-push hook warns them before they raise a pull request). See #148 .

**Comment by andrewgordstewart** [comment]
we could ask OWX or polycrypt for feedback on this and #148

**Comment by geoknee** [comment]
Documentation for `golangci-lint`: https://golangci-lint.run/usage/linters/#enabled-by-default-linters

**Comment by geoknee** [comment]
I've audited all of these items today, with the following conclusions:

- there is no linter supported by `golangci-lint` which enforces casing 
- of course the language itself is opinionated about the casing of the first letter of a variable or function
- mixedCaps is recommended by the "effective go" page https://go.dev/doc/effective_go#mixed-caps
- AFAICT all of our variables do in fact conform to this convention (even our constants since https://github.com/statechannels/go-nitro/pull/156)

I think these conventions are appropriately signposted by our linking to the effective go style guide. It's a shame we can't enforce them through linting. Also, by having enough code that conforms to the conventions (100% of it, ideally) any changeset which would break those conventions should hopefully be obvious. 

Yet, currently

- some filenames and directories have hyphens, which is bad because
  - it contravenes the above convention of effective go
  - it contravenes another convention about directories and packages having the same name #163
  
  These latter points are being addressed in #221
