### ISSUE TITLE
Refine demo frontend based on user testing

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1761]
- [ ]  I think the UI needs some kind of indication of having “found a payee node” and what that node is doing exactly. Because it’s kind of a delegation. “25 online payee nodes available now”
“You got matched with node ABC”

We could simply insert the phrase "Found 1 Retrieval Provider" or "Found DCENT Datacenter"

- [ ] Even if it doesn’t work yet “send $5 to get more payee node credits”

We could insert "Refresh the page to automatically get more credit. "

- [ ] Make it clear that the user is being given FREE MONEY to spend.

we could link to here https://calibration.filscan.io/en/address/0xe32d4B5C5a80660710f6a2aD3cB1c11664138F34/ , even better if we have verified the contract source code

- [ ] I didn’t know if I was going to get anything at first because there was no loading UI that I remembered.

the pay & download button could display "fetching..." until the file comes

**Comment by geoknee** [comment]
There's also a typo right at the top of the doc. "tesnet".

**Comment by geoknee** [comment]
We'd like a (?) symbol next to micropayments which links to a new subsection of the notion explainer.

**Comment by geoknee** [comment]
Let's put the price of each file next to the filename to bet upfront about how much money will be transferred.

**Comment by NiloCK** [comment]
nit: 402 error lists a payment amount but no units

**Comment by geoknee** [comment]
> When the file is downloaded it still defaults to the long filename. Is there a way to force it to default to the shortened, hardcoded names so that they match? I think its a little confusing when the filename you select on the UI does not match what gets downloaded to your machine

**Comment by geoknee** [comment]
> I was thinking perhaps (on mobile at least) it would be nicer to pop a new tab and display the image, rather than download the file.

**Comment by lalexgap** [comment]
> > I was thinking perhaps (on mobile at least) it would be nicer to pop a new tab and display the image, rather than download the file.

I attempted this in https://github.com/statechannels/go-nitro/pull/1774 by calling `window.open` but most it seemed to fail completely on mobile.
