### ISSUE TITLE
Ensure development / testing messaging cannot interfere with "production"/"staging" messaging 

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#1792]

**Comment by bitwiseguy** [comment]
The only way for a new node to connect to the existing "prod"/"stage" `messaging` network is if they explicitly attempt to make a connection to one of the node's `multiaddrs` that is already connected to the network. This can be done by providing a `multiaddr` in the `bootpeer` nitro configuration option. 

As far as I can tell, none of our current tests provide a cloud node's `multiaddr` to a new node when it is initialized, therefore the tests always create a new, isolated nitro network. [Here is one example](https://github.com/statechannels/go-nitro/blob/main/node_test/integration_test.go#L82C43-L82C43) showing our integration tests initializing nodes with a `bootpeers` list that is either empty, or only includes other test nodes.

**Comment by geoknee** [comment]
Thanks @bitwiseguy that was the conclusion I came to as well. Do you think what we have is sufficiently robust to keep the two networks separate? I suppose we could have an additional config param `localOnly` which just panics the node if it tries to connect outside of localhost. Might be overkill 🤷 

I did have a standalone docker container running on my machine which was pointed at a remote bootpeer. So that's another possible route to accidentally (or intentionally) connecting a local node to a cloud node / mixing the networks up.
