### ISSUE TITLE
Remove hardcoded Bob index

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#1807]
In `VirtualPaymentApp.sol` when a state with `turnNum = 2` is supplied, there is a check that Bob has signed the state:

``` solidity
require(
    NitroUtils.isClaimedSignedBy(candidate.signedBy, 2),
    'redemption not signed by Bob'
);
```

His index is hardcoded (`2`), which leads to unnecessary restraint of `VirtualPaymentApp` to single-hop case only.

Bob's index should be `fixedPart.participants[fixedPart.participants.length - 1]`.

**Comment by nksazonov** [comment]
> Perhaps we should be make it as clear as possible by computing Bob's index as an explicit constant.

by @geoknee

**Comment by geoknee** [comment]
Here's the source:
https://github.com/statechannels/go-nitro/blob/e19c9fb899dd729535ff040daafbe590d666811c/packages/nitro-protocol/contracts/VirtualPaymentApp.sol#L64

We should cut a new version of the npm package when this is fixed.
