### ISSUE TITLE
Consider adding `checkpointed` event

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#1830]
Currently `ForceMove` has `ChallengeCleared` event, which is emitted on every `checkpoint(...)` call. However, checkpoint can be invoked with no active challenge, so event name `ChallengeCleared` is confusing.

Nevertheless, I think we should have both `ChallengeCleared` and `Checkpointed` events, as it will be convenient to have different handlers for those events.

**Comment by nksazonov** [comment]
@geoknee , what do you think?

**Comment by geoknee** [comment]
I am in agreement. For some reason I feel tempted to try and do it with one event -- but thinking about it, I don't think there is any real benefit and we may as well have the two events.
