### ISSUE TITLE
Enforce testing pattern to prevent test interference 

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#187]
However, this test reaches into the `Channel` **pointed to** by the `DirectFundObjective` and calls a method (`.AddSignedState`) which mutates that `Channel`. Because we bypass the `Update/Crank` API (only possible because of a type assertion in this test), we lose the guarantee of a pure function.

Your solution here works because each test has its own `DirectFundObjective`. I do wonder, though, if we can add some annotations of adopt a pattern which makes these subtleties clearer in this test file? After all, one major benefit / motivation for having pure functions is the ease of testing and avoiding problems such as this.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/178#pullrequestreview-864742138_

**Comment by lalexgap** [comment]
This seems to be the same underlying issue as #314. Closing in favour of that.

**Comment by lalexgap** [comment]
Oops, accidentally commented on the wrong issue. Reopening.

**Comment by geoknee** [comment]
Closing this as I feel it is too vague to be actioned. I think the general pattern to avoid interference is to not share test data.
