### ISSUE TITLE
Design and implement a full ledger funding protocol

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#20]
Implement a full Ledger protocol. This would take the work from #223 and replace the "mock" ledger funding with a proper ledger protocol.

The goal of this task is to implement a full ledger funding protocol. We need to

- [ ] Figure out how the ledger funding protocol should look (the existing protocol in `server-wallet` could be useful) https://github.com/statechannels/go-nitro/issues/291
- [ ] Implement the ledger funding protocol
- [ ] Implement a test suite to test the ledger funding protocol

**Comment by wunnaii** [comment]
Andrew: is it necessary to build ledger protocol to complete this? Instead the engine can return a "success" response.
Colin: this exists in the tests for virtual fund. The sprint 3 goal is to explicitly include the ledger updates for the virtual funding integration tests.

**Comment by wunnaii** [comment]
The minimum amount of work to complete Sprint 3 goal, is to define an receive a request for ledger funding, and respond with "your request has been served".

**Comment by wunnaii** [comment]
We need to define an interface that can accept the existing ledger request, and output a response

**Comment by wunnaii** [comment]
Split this ticket into
1. "MVP" for virtual funding integration test
2. "real implementation" of protocol

**Comment by lalexgap** [comment]
I've updated this ticket to represent the "real implementation" and created #223 for the MVP

**Comment by andrewgordstewart** [comment]
Is there a way to link these issues so that this issue "depends on #223"?

**Comment by wunnaii** [comment]
if we wanna use zenhub again? I don't think even projects beta has that feature yet

**Comment by geoknee** [comment]
In favour of #296
