### ISSUE TITLE
Handle Message fails when receiving a new objective

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#201]
In this [PR](https://github.com/statechannels/go-nitro/pull/188) we started to sign states and send them out in a message.

However we're seeing  failure in the `client_test.go` as [HandleMessage](https://github.com/statechannels/go-nitro/blob/a0c3efb9a94492db6af28a0b4400d0a733a616d1/client/engine/engine.go#L92) assumes that `GetObjectiveById` will return an objective where in our case it doesn't.

I think this failure can be intermittent as it's possible for the test to complete before the message is received and causes an error.

**Comment by geoknee** [comment]
I'm addressing this in #202
