### ISSUE TITLE
Client test should assert on Direct Fund Objective results

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#205]
Currently the client test simply creates two clients and then kicks off a direct funding objective. However we don't assert on anything after starting the DF objective. This means that any failure in processing the DF objective could be ignored if the test completes first, which can lead to flickering tests.

 Instead we should wait for the progress to be made on the DF objective and assert on that progress. That would ensure that any errors generated while making progress on the objective would reliably be caught.

**Comment by geoknee** [comment]
via #208
