### ISSUE TITLE
We should rename the receiver variable to `o` for objective in our protocols

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#209]
Not affected by this PR, but I think we should rename the receiver variable to `o` for objective? `s` makes me think `state`...

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/188#discussion_r798402821_

**Comment by NiloCK** [comment]
Consistency and brevity are both good. I've enjoyed using `dfo` and `vfo` in contexts where either type of objective could be in play. `ddo` and `vdo` would follow by convention.
