### ISSUE TITLE
Ensure on-chain deposit requests are executed in an idempotent manner.

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#210]
> * If it's safe to deposit then a deposit `ChainTransaction` is returned in the side effects

We should make an issue to ensure that this action is idempotent. We can fire off a transaction, and then crank again before we receive confirmation of it being mined -- which risks sending another transaction. We can either manage idempotency in the protocol itself, or in the chain service.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/issues/188#issuecomment-1028837547_

**Comment by lalexgap** [comment]
This seems to be the same underlying issue as https://github.com/statechannels/go-nitro/issues/314. Closing in favour of that.
