### ISSUE TITLE
Add an `asBob` and `asIrene` unit test to the virtual fund single hop suite

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#218]
We currently have a good test for Alice. Writing one for Bob and/or Irene should therefore be easy. 

https://github.com/statechannels/go-nitro/blob/af0cfa0e545ed8bdfb8970d29a5ff3138881e593/protocols/virtual-fund/virtual-fund-single-hop_test.go#L356

**Comment by wunnaii** [comment]
2 days
