### ISSUE TITLE
Clearly separate client- and blockchain- data types

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#225]
Consider someone who wants to implement the on-chain components from the SATP specification.

They would need to:
- find the [relevant data types](https://github.com/statechannels/go-nitro/blob/a51b1cbb4ef00c43b7032d57d5c75d2ba04ee57a/channel/state/state.go#L33-L49)
- define these data types in Solidity
- implement the SATP interface using these data types

It is important that the data types used in Solidity are consistent with the data types linked above, which might not be obviously findable in our project.

We may wish to clearly separate data types that are used by a client to mutate data (eg. `Channel`, `State`) from those that are a part of how the protocol prescribes that states should be signed (eg. `FixedPart`, `VariablePart`)

For instance, we could place `FixedPart` and `VariablePart`, together with their respective encoders ([fixed part encoder](https://github.com/statechannels/go-nitro/blob/a51b1cbb4ef00c43b7032d57d5c75d2ba04ee57a/channel/state/state.go#L80-L85) and a [state encoder](https://github.com/statechannels/go-nitro/blob/a51b1cbb4ef00c43b7032d57d5c75d2ba04ee57a/channel/state/state.go#L109-L114)) in a separate package. (The `abi` package may be appropriate, I'm not sure.)

**Comment by lalexgap** [comment]
I think it could make sense to expose the whole [State struct](https://github.com/statechannels/go-nitro/blob/6e641130d071a814b543d2b9853070b2a693c530/channel/state/state.go#L21) as opposed to trying to pull out FixedPart and VariablePart. Hashing and signing rely on both variable and fixed parts and it's easier to deal with them together in one struct. If someone was to implement SATP I have feeling they'd end up writing a state struct similar to ours anways.

Our current `state.go` doesn't really focus on mutating data; it's mostly focused on sign/encoding/etc.. so I think it could be exposed as-is. It probably does make sense to move the state struct into a different package.

**Comment by lalexgap** [comment]
Closing, as I think this is pretty stale
