### ISSUE TITLE
Consider reorganizing tests into `package_test` packages

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#242]
A common Go practice is to create a separate package `foo_test` which tests the public api of package `foo`. Instead of this, we've been writing our tests directly inside their respective packages with the main motivation being:
- **access to package-private fields & methods**: we've been pretty aggressive about encapsulating protocol complexities so that the `engine` and `client` can treat them all generically. We desire access to internal objective state so that tests can probe it.
- **momentum**: we started out with these test locations. They worked well enough, so we kept going.

This has caused a pain point with the creation and sharing of test data. Summary of the problem is:

1. In the case of packages defining data structures (eg, `outcome`, `state`), it's not possible to declare test data that is reusable in other packages (where it is needed!) without making the data part of the public API of the package. 
2. When restricting test data for package `foo` to the package-private level in, say, `foo_test.go`, all variables created at the file scope become part of the global scope in this package, polluting that namespace. (Go does not have 'file scope' - packages can be considered single files for the most part)

The first is a total no-go. The second creates a deterrent - programming inside the package becomes more onerous (and error prone) as more labelled test data is added. And adding more labelled test data isn't even that useful since it is not exported!

This is all the worse because declaring fairly complex literal struct data in Go is burdensome. (Possibly opinion).

## Non-idea

In Typescript, this is a non-issue because circular dependencies are allowed. They are **not** allowed in Go. Preparing exportable test data of types defined in `foo` requires an import of `foo`, and so `foo` cannot re-import that data for its tests.

![image](https://user-images.githubusercontent.com/10780590/153989002-7ce880c2-0b44-4b84-a86f-a53fbbc39a63.png)

## Current idea

@geoknee came up with a couple of incremental improvements to the above statement of things:

1. place test data creation inside of individual test functions rather than at top-of-file as in our TS tests. This hides it from the global scope in the package.
2. amalgamate test functions inside one mega-function and use [`t.Run`](https://github.com/statechannels/go-nitro/blob/ac4b9cd0d5ab408345fe8f55f782efb95211b215/protocols/virtualfund/virtualfund-single-hop_test.go#L379) to call each individually. Now multiple tests have access to single-setup non polluting test data.

This still leaves us unable to declare test data in `foo` and use it in `bar`.

## Proposed Idea

The reusable test data pain goes away if we restrict to testing the public APIs of packages:

![image](https://user-images.githubusercontent.com/10780590/153899237-e2ada6c5-379b-415c-bb0a-e451a06aac22.png)

### Pros:
- lots of things can be declared in package `testdata` without polluting either internal or external namespaces
- some people feel strongly that only public APIs should be tested in general. Maybe hard-coding this is a net benefit, or tilts us toward better design choices and / or smaller packages
- at a glance, I'm not sure if we actually require access to package-private members or functions for the `directfund` or `virtualfund` tests. 
- ?

### Cons:
- in cases where we do find specific need for access to internals, test data may have to be duplicated inside that package
- ?

**Comment by geoknee** [comment]
We also have some examples of test code leaking across the public API of our production packages:
https://github.com/statechannels/go-nitro/blob/9933370da62948005b694ee8a5456bd769c4c783/protocols/ledger/ledger.go#L114

Another Pro of your proposal would be that (for example) the above function can live in a `ledger_test` package and still be used by other packages.

**Comment by andrewgordstewart** [comment]
Unfortunately, the current `testdata` package will cause circular dependencies:
- `testdata` must [depend on](https://github.com/statechannels/go-nitro/blob/114e60578b18cab886a1d279c399ea1428e3a237/internal/testdata/objectives.go#L6) `direct fund` if it wants to export a `DFObjective` helper that produces a `directfund.Objective`
- `directfund` must depend on `testdata` if it [wants to](https://github.com/statechannels/go-nitro/pull/434/files#diff-b7e6b47cfc49363e31028d4c11fe83d4c96e6f118370ad7fa9d31d5aad26ef27R104) use the `DFObjective` helper

Go does not allow cyclical dependencies, which limits the utility of a `testdata` package.

> In the case of packages defining data structures (eg, outcome, state), it's not possible to declare test data that is reusable in other packages (where it is needed!) without making the data part of the public API of the package.

Note that this isn't quite true: test data exported from `directfund/testdata/foo.go` (any dir called `testdata`) and test data exported from `directfund/exports_test.go` (any file ending in `_test.go`) are ignored by the go compiler. (These files are included when running `go test` -- see [the docs](https://pkg.go.dev/cmd/go@master#hdr-Test_packages))

This means we can export `TestOutcome` from either of these two files!

**Comment by andrewgordstewart** [comment]
For context, I ran into a circular dependency when trying to import `consensus_channel` into `virtualfund`, which is reasonable.

1. Currently, consensus_channel has a (minimal) [dependancy on testdata](https://github.com/statechannels/go-nitro/blob/14c6de7c8de4c63753adf23e2096d1cbbe504935/channel/consensus_channel/consensus_channel_test.go#L154).
2. `testdata` depends on `virtualfund`
3. Therefore, `virtualfund` cannot depend on `consensus_channel`

It is easy to break this cycle by removing the (minimal) dependency in (1). This made me wonder: how useful is `testdata`? 

For a given package `p`:
Type 1: either `testdata` exports mock data for `p`
Type 2: or `p` can use `testdata` to import mock data

(My problem above is that `consensus_channel` was type 1 and type 2.)

I think `client`, `client_test` should be type 2, and everything else should be type 1.

@NiloCK , is this the intention of `testdata`?
