### ISSUE TITLE
Update Ledger Request to include left and right amounts

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#244]
Yes - in SATP paper these are referred to as `a` and `b`, alice and bob's respective opening balances.

In general (and off-the-cuff - 80% certain), `a` wants to be deducted from the `left` role in the ledger and `b` deducted from the `right`.

_Originally posted by @NiloCK in https://github.com/statechannels/go-nitro/pull/236#r807199237_

**Comment by geoknee** [comment]
Good spot, I think this was an oversight when writing the `virtualfund` protocol -- due in part to the fact that the protocol doesn't need to think too much about the deductions to the ledger channels (only the additions). Of course the system as a whole needs to make those deductions fairly, hence this issue.
