### ISSUE TITLE
Make as much progress as possible during objective cranking

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#276]
If I haven't signed the prefund setup, I shouldn't necessarily return from cranking with `WaitingForCompletePrefund`:
https://github.com/statechannels/go-nitro/blob/c18042f84c322a59439bbbe9c5fb882f07bd2bf5/protocols/directfund/directfund.go#L145-L159

It might be that my signature actually unblocks the protocol and we can move to the next pause point. 

Making the change should also improve readability of the protocols.

The problem exists in both `directfund` and `virtualfund`.

**Comment by lalexgap** [comment]
It would be nice to add a new test for this as well when we make the change.IE:
- Sign all the pre/post fund setups and "fund" the channel
- Crank and make sure we complete
