### ISSUE TITLE
Investigate how integration test passed with an outcome between alice and irene

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#290]
You're right! I'm pretty surprised that things worked as is, we should investigate why that is.

_Originally posted by @lalexgap in https://github.com/statechannels/go-nitro/pull/274#discussion_r814928537_

**Comment by geoknee** [comment]
The virtualfund objective will interpret the 0th and 1st allocations as the parameters `a0` and `b0`. 
https://github.com/statechannels/go-nitro/blob/3a04d3ea896a44d0f9cb400d7602c87c89e58ab9/protocols/virtualfund/virtualfund.go#L156-L157

It would follow the SATP paper more faithfully, and tidy up this issue, if we _require_ that the 0th slot is the proposer (Alice, participant 0) and the 1st slot slot is their counterparty (Bob, participant n+1) when constructing the `virtualfund` objective.
