### ISSUE TITLE
Produce a design doc for a ledger sync protocol and decide on a solution

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#291]
The plan is to refresh ourselves on the [async virtual funding stuff](https://www.notion.so/statechannels/Asynchronous-virtual-funding-a2efa92c5b364c5586e97a4717a4aef3), and then consider some different options for engine design. It’s possible that this ends up making the engine simpler, as well as optimising the time to pay.

**Comment by geoknee** [comment]
https://www.notion.so/statechannels/The-ledger-protocol-at-the-end-of-Sprint-3-555c46cfa3df4e909438f8810eaff1c8

**Comment by geoknee** [comment]
Please check off when you have read and commented on the document: 
- [ ] Mike
- [ ] Alex
- [ ] George
- [ ] Colin
- [ ] Andrew

**Comment by geoknee** [comment]
(2 days)

**Comment by geoknee** [comment]
Soft decision is to go with a leader/follower update protocol in the ledger channels, which is achieved within a protocol crank. This solution will require us to have incoming message handlers _block_ until they can obtain a lock on the ledger channels which they want to own.

**Comment by geoknee** [comment]
Hard decision today aligns with the soft decision. Design doc here https://www.notion.so/statechannels/Leader-follower-ledger-channels-d0284683c80b48bda6cda427486c6a51 to be broken down into GH issues.
