### ISSUE TITLE
Improve integration test assertions (inspect each client's store on objective completion)

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#292]
Unfortunately the current API doesn't expose anything beyond the completed `ObjectiveId`. For now we could probably interrogate the `store` on the client to make sure states look like we expect them to.

_Originally posted by @lalexgap in https://github.com/statechannels/go-nitro/pull/274#discussion_r814937627_

**Comment by geoknee** [comment]
I think this plays into the old chestnut about on the one hand, testing only the public API; versus on the other hand reaching into the implementation to do some checks. 

We could provide a public API for getting states from the store?

We could also assert on the logs produced by the clients, as a medium-term testing strategy.

**Comment by andrewgordstewart** [comment]
The existing API is very barebones:
1. the `CreateVirtualChannel` returns only the objective's id
2. the `CompletedObjectiveEvent` contains only the objective's id
3. the client offers no API that lets its consumer see eg. how much capacity does it have with a particular intermediary?

The client API could offer different functionality, such as:
- when an objective is completed, some necessary information about the end result is included in the `CompletedObjectiveEvent`
- the client includes a `CurrentCapacity` API to allow its consumer to understand the capacity it has to make payments.

It would be good to think through a user story to understand these kinds of requirements. I can imagine useful APIs that also allow us to test the effects of a completed objective without leaking private or unwanted information through the API.

@lalexgap you did a lot of work previously on engine/wallet API. do you have any thoughts?

**Comment by lalexgap** [comment]
I think we should separate this into two problems:
- Having more thorough asserts in our integration test, so we feel more confident in the test. We could modify the API to do that or access the `Store` directly in the test. This is something we could do immediately.
- Crafting a well defined API for users to use. I think this should probably be tackled a separate issue. We could look at other examples of `golang` API as well as talk to potential users of the wallet. This probably requires some thought and consultation.

Some things to consider for our final API design:

Do we expect to have a payment/channel manager that wraps the wallet client? or do we expect users to interact with the wallet client directly? This will probably dictate the complexity of the wallet client.

How  should we communicate to a user when something is "done".  Do we expect users to listen subscribe to a single `chan` that fires an event for every completed thing (like `CompletedObjectiveEvent`)? Should an API call return a `chan` that will act like a promise and resolve when that particular thing is done?

**Comment by lalexgap** [comment]
Closing as our integration test has expanded to assert things both on the store and on the events returned.
