### ISSUE TITLE
Write a direct funding protocol

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#30]
Comply with the interface chosen when #14 resolves.

This is being worked on in https://github.com/statechannels/go-nitro/tree/direct-funder-rewrite.

# TODO
Left undone are:

- [ ] #50
- [ ] #51
- [ ] #57
- [ ] #52
- [ ] #53

**Comment by NiloCK** [comment]
Outstanding Qs:

For filecoin, presumably the only _asset_ in question is FIL. go-nitro has an exit-format style outcome defined in [channel/state/outcome/outcome.go](https://github.com/statechannels/go-nitro/blob/main/channel/state/outcome/outcome.go). The `DirectFundingObjectiveState` has single-asset style `MyDepositSafetyThreshold`, `MyDepositTarget`, and `FullyFundedThreshold` properties.

- Do we intend / want to use the outcome as-is, with the 0-address indicating whatever chain's native currency?
- Should the above properties be re-written as `[tokenAddress]: amount` maps to align with the exit-format?

(I hadn't thought much about the intersection of deposit safety thresholds and multi-asset channels - I guess the reasonable approach is to make one deposit tx when all assets have reached the safety threshold.)

**Comment by geoknee** [comment]
> * Do we intend / want to use the outcome as-is, with the 0-address indicating whatever chain's native currency?

I would say yes -- that's a relatively nice way to preserve compatibility with our solidity code which ought to handle FIL, too.

> * Should the above properties be re-written as `[tokenAddress]: amount` maps to align with the exit-format?

I would say also yes. At the cost of a bit more boilerplate now, we can preserve the option of having a multi-asset system in the future. I think it's worth it -- how do you feel?

 
> (I hadn't thought much about the intersection of deposit safety thresholds and multi-asset channels - I guess the reasonable approach is to make one deposit tx when all assets have reached the safety threshold.)

Yes I think this is reasonable. I think if you look at our[ existing code targeting Ethereum](https://docs.statechannels.org/contract-api/natspec/MultiAssetHolder#deposit), we only support one asset type per deposit. So it may be a) `n` transactions when all assets reach their safety threshold. Or it could be b) one transaction when each of the `n` asset reaches its safety threshold.

**Comment by andrewgordstewart** [comment]
This is being worked on in https://github.com/statechannels/go-nitro/tree/direct-funder-rewrite.

**Comment by NiloCK** [comment]
Closing, with follow-on issues created.
