### ISSUE TITLE
Explain the objectives <-> protocols connection

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#32]
Agreed that `Objective` needs explanation, particularly its relation to `protocols`. Let's make an issue to revisit this.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/29#discussion_r732067946_

**Comment by geoknee** [comment]
Adding a backlink here https://www.notion.so/statechannels/Protocol-interface-e076fe46c0774122818d1abb7cfd0c5a

**Comment by geoknee** [comment]
Via #59
