### ISSUE TITLE
ObjectivesToSpawn can become stale

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#338]
We originally construct the `ObjectiveToSpawn` in the [client](https://github.com/statechannels/go-nitro/blob/9f736c843d6ee097b2ead2f71ca7086500fa1dfb/client/client.go#L80) when the API is called. 

As part of constructing the virtual objective we [call](https://github.com/statechannels/go-nitro/blob/9f736c843d6ee097b2ead2f71ca7086500fa1dfb/protocols/virtualfund/virtualfund.go#L616) `GetTwoPartyLedger` to get the ledgers for the objective.

The problem is that there may be a delay between when we construct `ObjectiveToSpawn` and when the engine handles `ObjectiveToSpawn`.  This means that the ledger channels can become stale by the time the engine goes to handle `ObjectiveToSpawn`

An easy workaround can be seen [e9141f9](https://github.com/statechannels/go-nitro/pull/324/commits/e9141f908d9d0ccbab85870296d021fb8a8b4db3) where we simply refetch the ledger channels when the engine goes to process them.

I think a slightly better solution would move responsibility of constructing the objective to the engine, so it can construct it with the most recent data.

Instead of the Client generating full blown objective for `ObjectiveToSpawn` it could generate an `ObjectiveSpawnRequest` which contains enough information for the engine to generate the actual objective. This would mean that the client doesn't have to call `store.GetTwoPartyLedger`

**Comment by andrewgordstewart** [comment]
It does seem improper that the `client` would have to reach into the store!
