### ISSUE TITLE
GetTwoPartyLedger does not use channel store

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#339]
The current [implementation](https://github.com/statechannels/go-nitro/blob/9f736c843d6ee097b2ead2f71ca7086500fa1dfb/client/engine/store/mockstore.go#L126) of GetTwoPartyLedger iterates through channels off of `ms.Objectives`.

However these could be stale.  It should be looking in `ms.channels` to get the most recent channel.

**Comment by NiloCK** [comment]
This issue is addressed on my somewhat stuck serde branch, which has had debugging progress as recently as 15 minutes ago. Fingers crossed for a reviewable PR today
