### ISSUE TITLE
`virtualfund.ConstructObjectiveFromMessage` seeks incorrect ledger channel for `alice`

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#340]
Currently,
- an `alice` constructed vfo seeks the `I-B` ledger channel (should be `A-I`)
- `bob` or `irene` constructed vfo gives incorrect error messages when it fails to find its ledger channels

**Comment by lalexgap** [comment]
The reason this doesn't cause the integration test. to fail is that `alice` is always the one to start the virtual channel and thus construct it, so she never has to call `virtualfund.ConstructObjectiveFromMessage`.

**Comment by NiloCK** [comment]
As things currently stand, it's not possible for `bob` to initiate a virtual channel. From `virtualfund.go`:

```
func (c *Client) CreateVirtualChannel(...){
right, ok := (*c.store).GetTwoPartyLedger(*c.Address, intermediary)

	if !ok {
		// TODO: We need to implement proper API error handling
		panic(fmt.Sprintf("Could not find ledger channel for participants %v,%v", *c.Address, intermediary))
	}
```

If this is an intended long-term convention (vfo creator is always named alice & occupies `participants[0]`), then `virtualfund.CreateObjectiveFromMessage` should probably enforce `myAddress != alice`, which would make the `alice` case unreachable and removable.

**Comment by NiloCK** [comment]
per SU discussion March 16 (@NiloCK @andrewgordstewart @lalexgap), `virtualfund.CreateObjectiveFromMessage` should prohibit the creation of "alice-perspective" objectives.
