### ISSUE TITLE
CreateVirtualChannel only enables the creation of one virtual channel

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#345]
ChannelNonce is always set to `big.NewInt(0)` -- see: https://github.com/statechannels/go-nitro/blob/585fe7933bad95aa1fe0cd35a081da8b070edc82/client/client.go#L84

This means that calling `CreateVirtualChannel` twice with the same input will create an objective that immediately succeeds.

**Comment by lalexgap** [comment]
We are now using [random nonces](https://github.com/statechannels/go-nitro/blob/36203635b6985d4c3db28cd926754d3b80e347b0/client_test/virtualfund_integration_test.go#L39) which allow for multiple virtual channels.We have a separate issue(#348) for more sophisticated nonce management.
