### ISSUE TITLE
Determine nonce management

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#348]
How do we want manage nonces? Should the client be responsible for generating the nonces or should the API just accept a nonce.

**Comment by lalexgap** [comment]
An alternative is to expect the API to provide a Nonce. IMO, this is better than leaving a TODO, which in my experience is easy to forget about.

Having the client API require the nonce means:
- if it's a bad design, we will hear complaints about it
- users can actually use the nonce as an idempotency key

_Originally posted by @andrewgordstewart in https://github.com/statechannels/go-nitro/pull/341#discussion_r827244832_

**Comment by geoknee** [comment]
> Having the client API require the nonce means:
> 
> * if it's a bad design, we will hear complaints about it

This has indeed happened 🔮 . We decided to today that we need to bring nonce management inside the `go-nitro` client to have greater control (e.g. over the range of random number generated, or to ensure no collision with a previously used nonce).
