### ISSUE TITLE
Running Large amount of tests fails due to open log file handles

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#375]
```
❯ go test ./client_test -count=1000
2022/03/21 18:33:34 open ../artifacts/virtualfund_client_test.log: too many open files
```

**Comment by andrewgordstewart** [comment]
I believe the current integration test creates one open file `f` per client, but each `f` is opening the same filename.

**Comment by geoknee** [comment]
@lalexgap can you give a bit more context on why you might want to run so many tests concurrently?

**Comment by geoknee** [comment]
Discussed in standup: the `-count=N` flag seems pretty useful for unit tests, but maybe less so for integration tests which may be more resource hungry (think log files, database connections, etc). So one solution may be to silo integration tests away from unit tests, so they can be run with different test parameters.
