### ISSUE TITLE
Investigate Logging options

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#377]
Look into using a logging library instead of the golang log library.

Some nice features we may want:
- Various log levels
- Logging go-routine ids (for #378)
- Json output for easy parsing?

**Comment by geoknee** [comment]
One option : https://github.com/Sirupsen/logrus, which should be very easy to swap in (uses the same API as the standard go logger).

**Comment by NiloCK** [comment]
go nitro has a logger
