### ISSUE TITLE
Implement ConsensusChannel.Propose

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#392]
If an objective managed by the leader wishes to use a consensus channel `L` (eg. [here](https://github.com/statechannels/go-nitro/blob/e536d0e8824f90ff359ceafdbc9070ed9957bfe3/protocols/virtualfund/virtualfund.go#L636-L642)), it can call `L.Propose(someUpdate, pk)`. The consensus channel should:
1. construct the **last** proposed state, starting with the consensus state and applying each proposed update in order
2. Sign the proposed state
3. Put the signed proposal in the queue
4. Return the data required to construct a `SideEffect`'

**Comment by lalexgap** [comment]
@andrewgordstewart Is this completed by https://github.com/statechannels/go-nitro/pull/373?

**Comment by andrewgordstewart** [comment]
I would say no: for instance, we discussed that a `ConsensusChannel` will likely need to store an objective id in its `proposalQueue`, and #373 does not do so.

**Comment by andrewgordstewart** [comment]
Actually, maybe it's fine to leave storing an objective id for now -- we can always add that in later when required!

What's missing at the moment is some tests! I'll assign myself to it and write these tests.

**Comment by andrewgordstewart** [comment]
finished by #407
