### ISSUE TITLE
Flickering test

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#397]
https://github.com/statechannels/go-nitro/runs/5681630182?check_suite_focus=true failed with
```
=== RUN   TestMultiPartyVirtualFundIntegration
[326](https://github.com/statechannels/go-nitro/runs/5681630182?check_suite_focus=true#step:6:326)
    helpers_test.go:60: Objective ids [VirtualFund-0x7bb8b17b00ade20050a23f8177c04b4f8ac76101c8d880f20a28f5f10c4f737c] failed to complete on client 0xBBB676f9cFF8D242e9eaC39D063848807d3D1D94 within 1s
```

This PR did not touch any existing code, and re-running made the test pass.

**Comment by lalexgap** [comment]
Mostly likely #366 as the multi-party test is still vulnerable to it but the limited amount of channels makes it much less likely.

Maybe for now we should add a `panic` when a follower receives a ledger proposal out of order. This would at least let us attribute any flickering to a specific problem we know about. It probably makes sense to disable this test for now as well to avoid the flickering.
