### ISSUE TITLE
Which types/functionality should be exported from consensus_channel?

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#408]
The `consensus_channel` was created before I had fully internalized what it means to name something with a Capital letter -- I chose to export things based on:
- types should be Capitalized (because of my familiarity from Typescript)
- functions should be Capitalized (because I mostly noticed Capitalized functions elsewhere in `go-nitro`)

A decent amount of functionality from `consensus_channel` shouldn't be exported (eg. `ConsensusChannel.MyIndex`).

Is it a good rule of thumb to leave variables and types as un-exported until we know that they should be a part of the external interface of a package?

**Comment by geoknee** [comment]
> Is it a good rule of thumb to leave variables and types as un-exported until we know that they should be a part of the external interface of a package?

Yes.
