### ISSUE TITLE
Table tests for leader channel

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#417]
General comment: I found this test pretty hard to read. I think that is because test data, helper functions, API calls  and assertions aren't organised very well. 

I'm wondering if a table test or something would help? Something which looks a little more like this when I scan it:

```
0[ ] + Propose(1) = 0[1]
0[1] + Propose(2) = 0[1,2]
0[1,2] + Propose(3) = 0[1,2,3]
0[1,2,3] + UpdateConsensus(2) = 2[3]
2[3] + UpdateConsensus(3) = 3[ ]
```

Here I'm using a notation like `consensusTurnNum.ProposalQueue` (I think you get the idea).

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/410#discussion_r836384672_

**Comment by geoknee** [comment]
Here's an example of an existing table test https://github.com/statechannels/go-nitro/blob/main/channel/consensus_channel/serde_test.go
