### ISSUE TITLE
The `store` doesn't properly store/retrieve the outcome

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#435]
Currently it looks like the `LedgerOutcome` that comes back has a zeroed out destinations.

**Comment by lalexgap** [comment]
I think this is due to `LedgerOutcome` only containing private fields. `The raw json string seems to not include any private fields:
```{"Id":[43,102,29,60,92,242,199,232,69,165,154,35,101,113,70,211,0,173,136,123,102,86,197,26,145,39,100,224,102,56,245,60],"MyIndex":0,"FP":{"ChainId":0,"Participants":["0xaaa6628ec44a8a742987ef3a114ddfe2d4f7adce","0xbbb676f9cff8d242e9eac39d063848807d3d1d94"],"ChannelNonce":37140676580,"AppDefinition":"0x5e29e5ab8ef33f050c7cc10b5a0456d975c5f88d","ChallengeDuration":60},"Current":{"TurnNum":0,"Outcome":{},"Signatures":[{"R":"ixqul6ghVVjVQ1HHfpLyXhz6F7qZ/tzjW1m6Koiq1Uo=","S":"XYJDKQ67hVpr8v/CIa9HlBd6FZLQLwJPy10fxNg1TJI=","V":0},{"R":"rKC5Yz2hL4oiHTUb+kuKQBDCp7QYad6+KNmXt9KmeyQ=","S":"CqPy+y0SchbHyDWf9wC554KVyD0X6NNcoZ6EUj8t9qA=","V":0}]},"ProposalQueue":[]}
```

If I change the LedgerOutcome fields to be public I start seeing them show up in the generated JSON.

**Comment by geoknee** [comment]
I've started looking into this. The private fields are an issue, but not the only issue! I'll start by writing some explicit serde tests for a consensus channel.
