### ISSUE TITLE
Clarify that `testdata` package should not be imported into implementation packages

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#438]
From discussion in #434 about cyclic dependency issues after importing `consensus_channel` into `protocols/virtualfund`:

This is more or less as-expected.

![image](https://user-images.githubusercontent.com/10780590/160875174-c5280724-7549-4a4d-af4c-bb774d5f7a6f.png)

`package consensus_channel` currently tests inside `package test_channel`. Per #242, the `testdata` package should be consumed by dedicated test packages rather than implementation packages in order to avoid these import cycles.

_Originally posted by @NiloCK in https://github.com/statechannels/go-nitro/issues/434#issuecomment-1083308329_

**Comment by andrewgordstewart** [comment]
> Eg., a consensus_channel_test also cannot use testdata, since it would add a virtualfund <- consensus_channel <- consensus_channel_test <- testdata <- virtualfund cycle, right?
> 
> Or, did I miss something?

🤦 Of course, `consensus_channel` would not depend on `consensus_channel_test`. ie. there would be no cycle
