### ISSUE TITLE
We are not able to serialize `big.Ints`

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#439]
Because:
* they have unexported fields
* we do not control the type so cannot have it implement `json.Marshaler`

Needless to say this is a pervasive type in our codebase so figuring out how to serialize them is highly critical. 

The most obvious solution is to replace `big.Int` with our own type (which can embed a `big.Int`). We may need to do a big find+replace job to implement that solution.

**Comment by geoknee** [comment]
I think the short answer is that the failures are silent (no errors or panics), and we don't have goo enough tests / wide enough coverage to catch this.

**Comment by lalexgap** [comment]
I think we ran into issues with `big.Int` marshalling because we weren't using pointers to big ints. The `MarshalJson` function expects a pointer [receiver](https://pkg.go.dev/math/big#Int.MarshalJSON)
