### ISSUE TITLE
Is it a problem that`*big.Int` gets marshalled to a plain old number?

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#452]
Interesting that `*big.Int` gets marshalled to a plain old number. We should think about whether that may cause us problems when the numbers are big! It may only be an issue when wanting to use the JSON in (say) javascript.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/449#discussion_r839319962_

**Comment by NiloCK** [comment]
I believe it marshals as text, not a #.

`big.Int.MarshalJSON()` returns `big.Int.MarshalText()`, which ends up at `itoa`

From https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/math/big/natconv.go;drc=refs%2Ftags%2Fgo1.18;l=263 :

![image](https://user-images.githubusercontent.com/10780590/161064380-f9a2fa34-eac5-4889-8c5a-bdd203847a69.png)


![image](https://user-images.githubusercontent.com/10780590/161063672-7853b8e5-e78d-4b4b-9886-f30a60c2806e.png)

(Apologies for screenshot-of-text. Copying from that viewer includes a bunch of markup as well as the text)

**Comment by geoknee** [comment]
I think it marshals as text in the sense of JSON being a textual format. But if you take a look at

https://go.dev/play/p/rQRuSHOIrHc

You can see that even a huge number ends up like

```json
{"SomeKey":81129638414606753753383043072016}
```

rather than
```json
{"SomeKey":"81129638414606753753383043072016"}
```
or some other format. In our typescript code we would typically convert BigNumbers to hex strings when serializing. I think such JSON would not be ingestible by javascript code, for example?

**Comment by geoknee** [comment]
(I think it is ok if we keep things within Go, though https://go.dev/play/p/WOWcGgDsJxJ ).

**Comment by NiloCK** [comment]
Interesting. Yeah, it seems a little wonky that marshaling into JSON doesn't account for JS interop, or, that it allows for smooth JS interop only in the case of bigInts that aren't bigger than JS ints.

JS does have native BigInts now - maybe expected usage of marshalled Go bigints is to pass them into a custom parser?

JS experiment with somewhat confusing results:

```
big = BigInt(987987987987987987987987987987987987987987987987987987987987987987987987987987987)
> 987987987987987964610968926924560462878922914509867405692029503396201923648421888n
parsed = JSON.parse(987987987987987987987987987987987987987987987987987987987987987987987987987987987)
> 9.87987987987988e+80
typeof big
> "bigint"
typeof parsed
> "number"
big == parsed
> true
big++
> 987987987987987964610968926924560462878922914509867405692029503396201923648421888n
big == parsed
> false
parsed++
> 9.87987987987988e+80
big == parsed
> false
```

**Comment by NiloCK** [comment]
The above JS BigInt experiment is bunk!

I hadn't noticed that the initial bigint construction "failed" due to overflow, and its received value was equal to what was produced by `JSON.parse`.

Wrapping the initial BigInt input in quotes (making it a string) corrects this, and then `big == parsed` returns false, as expected.
