### ISSUE TITLE
Should store.GetConsensusChannel require only a `counterparty` as input?

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#457]
Currently:

```
type ConsensusChannelStore interface {
	GetConsensusChannel(leader, follower types.Address) (channel *consensus_channel.ConsensusChannel, ok bool)
	SetConsensusChannel(*consensus_channel.ConsensusChannel) error
}
```

requires the calling code to know in advance whether the calling client is the leader or follower in this particular ledger channel.

Is:

```
type ConsensusChannelStore interface {
	GetConsensusChannel(counterparty types.Address) (channel *consensus_channel.ConsensusChannel, ok bool)
	// ...
}
```

a better API? This removes the above requirement, and allows calling code to inspect the returned channel for leader / follower designation.

**Questions**:
1. are there cases where we expect to store / retrieve ledger channels in which we are not participants? (I don't think so.)
2. should this API give much consideration to the possibility of multiple existing channels between two given actors?

**Comment by andrewgordstewart** [comment]
> 1. are there cases where we expect to store / retrieve ledger channels in which we are not participants? (I don't think so.)

No

> 2. should this API give much consideration to the possibility of multiple existing channels between two given actors?

I think we can currently assume there is one channel between two actors.
