### ISSUE TITLE
Commit an ADR on how to migrate from using "union types"

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#461]
# Context
Many types of proposals need to be serialized & deserialized, in order to be sent across the wire.

```
p1 = Add{guarantee}
p2 = Remove{guarantee}
p3 = TopUp{...}
```

A ConsensusChannel may modify its outcome by receiving these proposal:

```
sp_leader = leader.Propose(p1)

follower.Receive(sp1_leader)

_ = 1follower.SignNextProposal()

sp3_leader = leader.Propose(p3)

follower.Receive(sp3_leader)

sp3_follower = follower.SignNextProposal())

leader.UpdateConsensus(sp_follower)
```

A `message` might include any such type of proposal.
```
m1 = {
  id: "ledgerTopUp-143",
  proposal: sp3_follower
}

m2 = {
  id: "virtualfund-0xf00",
  proposal: sp_leader
}
```

Coming from typescript, we handled this type of situation with a combination of JSON schema definitions and generics.

## Problem

It is unclear how proposals, messages etc should be passed around as values.

Complications arise especially when serializing/deserializing these values: when `m2` is received, how does one determine which `UnmarshalJSON` function to call?

### 1. Empty interface
A `SignedProposal`, `Message` etc could hold an empty interface
```
type SignedProposal struct {
  Proposal interface{}
  Sig state.Signature
}

type Message struct {
  ObjectiveId string
  Data interface{}
}
```
In this case, `Proposal` & `Data` can be any type, and some combination of reflection, type inspection, or data inspection.

### 2. Poor man's sum type
A flexible type could pretend to be a sum type
```
type Proposal {
  Add Add
  Remove Remove
  TopUp TopUp
}

type SignedProposal struct {
  Proposal
  Sig state.Signature
}
```

In this case, something that uses a SignedProposal should probably check that exactly one of `Add`, `Remove` and `TopUp` are present.

### 3. Generics
Generics were recently added and may provide another option

# Action

If possible, explore how other codebases solve this problem. Commit an ADR with our solution.

**Comment by andrewgordstewart** [comment]
https://github.com/statechannels/go-nitro/pull/454 is related

**Comment by andrewgordstewart** [comment]
go-perun uses Option 1 (more or less) in their `wire` package:
- a `Msg` is an interface that implements `Type()`: https://github.com/hyperledger-labs/go-perun/blob/15c5f92a0ca4d40b18214a69c8cb427d996a5852/wire/encode.go#L30-L33
- during initialization, decoders are [registered](https://github.com/hyperledger-labs/go-perun/blob/15c5f92a0ca4d40b18214a69c8cb427d996a5852/client/proposalmsgs.go#L34) by the `wire` package. They are stored in [a global variable](https://github.com/hyperledger-labs/go-perun/blob/15c5f92a0ca4d40b18214a69c8cb427d996a5852/wire/encode.go#L71)

decoding a message is then a two-step process:
1. first, the type is [read and validated](https://github.com/hyperledger-labs/go-perun/blob/15c5f92a0ca4d40b18214a69c8cb427d996a5852/wire/encode.go#L60-L67)
2. then, the message is [decoded](https://github.com/hyperledger-labs/go-perun/blob/15c5f92a0ca4d40b18214a69c8cb427d996a5852/wire/encode.go#L68) by that type's decoder

**Comment by NiloCK** [comment]
Perun's Decode function:

https://github.com/hyperledger-labs/go-perun/blob/15c5f92a0ca4d40b18214a69c8cb427d996a5852/wire/perunio/serialize.go#L89

**Comment by geoknee** [comment]
On option 3:

We have already started using some features of "Go generics", including type constraints which have a sort of union type within them:

https://github.com/statechannels/go-nitro/blob/91dfba76fe250cf7d7e8bea92c6f17ed4d49a6c2/protocols/messages.go#L176-L181

I think these are not a direct drop-in for TS-style union types, however. But I would like to understand better what they can do for us and whether we should spread them around the codebase some more.

**Comment by lalexgap** [comment]
Closing this as we've already implemented a mix of 2/3. I don't think we need an ADR at this time.
