### ISSUE TITLE
Implement and test Virtual Defunding Protocol

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#463]
The goal of this issue is to implement and test a full virtual defunding protocol. 

- [x] https://github.com/statechannels/go-nitro/issues/477
- [x] https://github.com/statechannels/go-nitro/issues/478
- [x] https://github.com/statechannels/go-nitro/issues/480
- [x] https://github.com/statechannels/go-nitro/issues/479
- [ ] https://github.com/statechannels/go-nitro/issues/564

**Comment by lalexgap** [comment]
This is now completed
