### ISSUE TITLE
Update VariablePart to match off-chain code

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#499]
@nksazonov This struct needs updating, too, I think?

Take a look at 744dbbef0ef22ba8085d60b8b0a8b468f038bc16 and 3b4bfbae06a4e5942ca2d88d80c2af1cea15740c

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/427#discussion_r843108788_

**Comment by nksazonov** [comment]
@geoknee why don't also add `turnNum` and `isFinal` fields to `VariablePart` as was done in [`744dbbe`](https://github.com/statechannels/go-nitro/commit/744dbbef0ef22ba8085d60b8b0a8b468f038bc16) you have sent?

This would make the code significantly clearer and function signatures would resemble ones from SATP paper more.

**Comment by nksazonov** [comment]
I am thinking about adding `exitsEqual` method to `ExitFormat` to enclose outcome comparisons (as in [`3b4bfba`](https://github.com/statechannels/go-nitro/commit/3b4bfbae06a4e5942ca2d88d80c2af1cea15740c#diff-0f9a53252feac4825a0d3108507d0fd4aad893bd91361bb492e9cdf74fb5fb77R46)).
It would be a bit more gas efficient and a clearer way (without invoking [5 functions in one line](https://github.com/statechannels/go-nitro/commit/3b4bfbae06a4e5942ca2d88d80c2af1cea15740c#diff-0f9a53252feac4825a0d3108507d0fd4aad893bd91361bb492e9cdf74fb5fb77R46)).

@geoknee what do you think?

**Comment by geoknee** [comment]
> I am thinking about adding `exitsEqual` method to `ExitFormat`

Yes I think this is a good idea. I suppose we can split your suggestion into two components:
1. Refactor the "encode and hash" equality check into a helper that lives in `ExitFormat`.
2. Change the implementation to be more gas efficient.

**Comment by nksazonov** [comment]
> I did something like 1 (but kept it in this repo) on a branch I have been working on: https://github.com/statechannels/go-nitro/compare/go-solidity-signature-test?expand=1#diff-483aad04b1f90d19c78f0fd86f7ebb7869c6c194797c3d0774ce9e80dff5a2b8R632-R647

This link leads to a PR, unfortunately not a difference comparison as it might suggest. 
Could you specify the commit, file and lines, please?

**Comment by geoknee** [comment]
Yes, sorry, I updated the link to something more useful!

**Comment by nksazonov** [comment]
> 2. Change the implementation to be more gas efficient.

I suggest we use `_bytesEqual` from `ForceMove.sol` instead of `keccak256` comparison. Would it be OK to copy-paste that function to `ExitFormat`?

**Comment by geoknee** [comment]
Via #508
