### ISSUE TITLE
Investigate keeping data in `calldata` if possible.

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#527]
It might save some gas. 

---

I did a bit of digging: https://github.com/ethereum/solidity/issues/9160

At solidity 0.7.4, the functionality to copy data from `calldata` to `memory` for a struct (which we would need to do because e.g. `requireStateSupportedBy` takes a `FixedPart memory fixedPart`) was unimplemented. 

I believe it was implemented from 0.7.6.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/508#discussion_r848550512_

**Comment by nksazonov** [comment]
> At solidity 0.7.4, the functionality to copy data from calldata to memory for a struct (which we would need to do because e.g. requireStateSupportedBy takes a FixedPart memory fixedPart) was unimplemented.
>
> I believe it was implemented from 0.7.6.

But then it is unclear why the contracts can be compiled successfully before we introduced changes to `VariablePart` struct and `ForceMove` function signatures.

**Comment by nksazonov** [comment]
[Solidity 0.7.6](https://github.com/ethereum/solidity/releases/tag/v0.7.6) fixes a lot of `calldata` related issues indeed: 

>  Code generator: Support conversion from calldata slices to memory and storage arrays.
    Code generator: Support copying dynamically encoded structs from calldata to memory.
    Code generator: Support copying of nested arrays from calldata to memory.
