### ISSUE TITLE
Return `SideEffects` from `DirectFundObjective.Crank()`

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#53]
The `DirectFundObjective.Crank()` method does not currently return any nontrivial `SideEffects`. This prevents an integration test from succeeding. 

To close this issue, we should return proper side effects (rather than `NoSideEffects`). The types / interfaces for those side effects may or may not need to change. 

Example: 

https://github.com/statechannels/go-nitro/blob/543c6dcf0e000e6de96b5f3f3871cddb7e8f37c1/protocols/direct-fund/direct-fund.go#L136-L140

---
(edited by @geoknee )

**Comment by geoknee** [comment]
This issue should cover adding unit tests for returning the right `SideEffects` from the `Crank()`.

**Comment by lalexgap** [comment]
@geoknee/ @NiloCK  Can the direct fund objective be responsible for signing a state and adding the signature to the `channel`? Or should the signature request be a`SideEffect`?

**Comment by geoknee** [comment]
> @geoknee / @NiloCK Can the direct fund objective be responsible for signing a state and adding the signature to the `channel`? Or should the signature request be a`SideEffect`?

The signature does not need to be a side effect, so it should be done synchronously during the `.Crank()`.
