### ISSUE TITLE
Clarify SignNextProposal

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#531]
Not wrt this PR, but a clarification: usage here is along the lines of:

`expectedProposal` is the follower's locally computed proposal, which is compared against the leader-supplied enqueued proposal, in order to validate that leader-supplied proposal.

?

Maybe a name like "ValidateNextProposal", "RatifyNextProposal", "[Verb]QueuedProposal" is better.

_Originally posted by @NiloCK in https://github.com/statechannels/go-nitro/pull/521#discussion_r848566143_

**Comment by lalexgap** [comment]
Closing as this is very stale.
