### ISSUE TITLE
Fix eslint errors, add .js files to eslint

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#554]
After adding eslint workflow, not all files have been fixed (e.g. `hardhat.config.ts`). Moreover, several files (configs mostly) have `.js` extension, which means they are not checked by eslint.

**Comment by nksazonov** [comment]
@geoknee why does eslint check only `src/**/*.ts`, but not the whole `nitro-protocol` directory?

[From `package.json` L12:](https://github.com/statechannels/go-nitro/blob/main/nitro-protocol/package.json#L12)
```json
"lint:check": "npx eslint \"src/**/*.ts\" --cache && npm run solhint:check",
```

**Comment by geoknee** [comment]
I don't think there is a good reason for this. Probably just that our standards are lower for test code! It would definitely be better to lint everything, unless this throws up a ton of errors that take a lot of pain to sort out.
