### ISSUE TITLE
Migrate to a newer solidity version

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#556]
> @geoknee , what do you think of bumping contracts to the latest solidity version? It seems to have a lot of fixes and gas optimizations. Moreover, staying at old solidity version blocks us from using newer versions of libraries (e.g. openzeppellin), in which optimizations or even fixes are introduced.

Yes it is probably a good idea to do that. The existing contracts have been audited, which I think generally disincentivizes changing the compiler version; but given the reasonably large changes upcoming in #496 and the other advantages you mention, I think I'm in favour of upgrading.

One nice thing will be that we will no longer need to import `SafeMath`, since that was absorbed into the language since `0.8.0`.

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/issues/552#issuecomment-1102491608_

**Comment by geoknee** [comment]
https://github.com/statechannels/go-nitro/pull/829#discussion_r949508010
