### ISSUE TITLE
Modify the `ForceMoveApp` interface to support `latestSupportedState` and integrate it into `ForceMove.sol`

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#557]

**Comment by nksazonov** [comment]
Thinking before making any code changes...

`latestSupportedState` function interface is reliant on both `FixedPart`, described in `IForceMove.sol` and `VariablePart`, described in `IForceMoveApp.sol`. This already introduces cross-chain dependencies, which is not good.

Moreover, in a ForceMoveApp developer must implement `latestSupportedState`, which means every time they use `FixedPart` or `VariablePart`, a dev would need to specify either `IForceMove.FixedPart` or `IForceMoveApp.VariablePart` - not only excessive code, but a bit confusing one.

I propose a separate interface with all state channels related structures described in it to be introduced. @geoknee , what do you think?

**Comment by geoknee** [comment]
1. I agree that it is awkward currently that `FixedPart` and `VariablePart` are not defined in the same contract. 
2. What do you mean by "cross chain dependencies?
3. What would the developer need to use in your proposed interface? Something like `NitroTypes.FixedPart` and `NitroTypes.VariablePart` ?

**Comment by nksazonov** [comment]
> What do you mean by "cross chain dependencies?

On one hand we have `ForceMove.sol` with `FixedPart` described and `IForceMoveApp` used inside of this contract as `IForceMoveApp.VariablePart` and `IForceMoveApp.latestSupportedState`. On the other hand, `IForceMoveApp` with `VariablePart` defined and `IForceMove.FixedPart` used. This is related to your 1st point and just seems odd.

> What would the developer need to use in your proposed interface? Something like NitroTypes.FixedPart and NitroTypes.VariablePart ?

NitroTypes interface with all structs described can either be explicitly addressed (as you propose, NitroTypes.FixedPart) or inherited by `IForceMove` and `IForceMoveApp` (so as structs will be available right on).
Personally, I opt for the second option as explicit addressing would be useless here.

**Comment by geoknee** [comment]
Sounds good to me. Probably not a lot of work to knock together a prototype.
