### ISSUE TITLE
Writing a `VirtualChannel` application conforming to the new `ForceMoveApp` interface 

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#559]
See https://www.overleaf.com/project/618a7979d3893c93c6f7a931 or https://github.com/statechannels/go-nitro/discussions/764#discussioncomment-3053372.

The work should include:
* A typescript test in the `./nitro-protocol/contracts/tests` sub dir.
* Checked-in go-bindings for this new contract which are available for the chain service to use. See for example:

https://github.com/statechannels/go-nitro/pull/676/files?file-filters%5B%5D=.sh&show-deleted-files=true&show-viewed-files=true#diff-3ac5afd992608bf76f556ef1f83e3394e068f4a2a59d11af8f7c95894639ce41

We can reuse / replace `EmbeddedApp.sol`.

**Comment by andrewgordstewart** [comment]
Specifications for the app channel rules can be found [here](https://www.notion.so/statechannels/Payment-channels-74496936061c467e91a6d21285b04304#a57832db438f4232b6085c83cd48f27d)
