### ISSUE TITLE
If the engine panics no logs are written out

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#568]
Currently when the engine panics we don't write the file to the log destination. Since the `engine` panics on any [error](https://github.com/statechannels/go-nitro/blob/5e4b8b105e193b92fc81818a8dadfe7cce9bd3d8/client/engine/engine.go#L115), it means we won't have logs available when we're debugging the error.

**Comment by geoknee** [comment]
https://github.com/golang/go/issues/41355
