### ISSUE TITLE
Make infrastructure for inter-wallet tests of protocols

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#57]
As a rough outline, test suite should aim to recreate some of the [test-with-peers](https://github.com/statechannels/statechannels/tree/master/packages/server-wallet/src/__test-with-peers__) functionality from the typescript server-wallet.

Some additions that could be useful and not too painful given the golang environment:

- [x] lightweight simulation of network communication via wallets communicating through go chans (see #109)
- [ ] some fuzz / property testing via go's builtin [testing/quick](https://pkg.go.dev/testing/quick) package

**Comment by geoknee** [comment]
@NiloCK can I suggest that we take the fuzz testing component and convert into a separate issue? And then close this one?

I think we have the infrastructure we need, now, and what remains is writing the test and getting it to pass.

**Comment by NiloCK** [comment]
Yeah, absolutely.

**Comment by geoknee** [comment]
#168
