### ISSUE TITLE
Flickering test around chain events

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#608]
A flicker can be seen [here](https://github.com/statechannels/go-nitro/runs/6198391047?check_suite_focus=true).

It looks like the error occurs when  [casting a chain event ](https://github.com/statechannels/go-nitro/blob/main/protocols/directdefund/directdefund.go#L195:L195).  It seems that the direct defund integration test ended up receiving a `DepositedEvent` which it can't cast to a `AllocationsUpdatedEvent`.

**Comment by geoknee** [comment]
Let's see if we can grab some logs next time this happens (can't seem to find any from the above runs).

**Comment by geoknee** [comment]
Two thoughts: 

1. We could simply choose not to error (which is actually a panic) when an objective gets passed an event that it doesn't know how to handle (or care about). It doesn't seem that indicative of something "really going wrong", since we don't do anything very smart with routing events from the chain to the objective -- we just send it to whichever objective currently owns the channel. 

2. The race condition seems to distill down to: a deposit event is sent to an engine _after_ the directfund objective completes. Is this because the directfund objective didn't actually "pull" the event, or because the chain or chainservice managed to "push" it to the engine more than once?

**Comment by lalexgap** [comment]
>The race condition seems to distill down to: a deposit event is sent to an engine after the directfund objective completes. Is this because the directfund objective didn't actually "pull" the event, or because the chain or chainservice managed to "push" it to the engine more than once?

I think the problem is that the directfund objective (and probably the directdefund objective) can submit multiple transactions depending on the order chain events and messages arrive in.

For example let's assume we have a direct fund objective:
- Alice and Bob exchange prefund setups
- Alice submits transaction to the chain to deposit.
- Bob detects Alice's chain event. Bob submits a transaction to chain now that it's safe for him to deposit.
- Alice detects Bob's chain event and sends post fund setup.
- Bob receives post fund setup. This causes Bob to crank again. Since Bob **has not received  his own chain event yet** he submits another transaction
- Bob detects one of his chain events and signs the post fund setup.
- Alice and Bob move onto direct defunding, eventually Alice receives Bob's second chain event and blows up.


The problem is that we rely on  [checking the current balances](https://github.com/statechannels/go-nitro/blob/c5999a1cb9a880640fcd661322e1f21f29614eb4/protocols/directfund/directfund.go#L264) to determine if a client should submit a transaction. However these balances only get updated when a chain event is received. So if `Crank` gets called multiple times before Bob detect's his own chain event, he will submit multiple transactions.

Previously I think we used a boolean flag on the objective to indicate whether a transaction has been submitted or not. We could implement something like that to avoid this problem (perhaps we could use a `TransactionId` so we could also query the status of the transaction?)

**Comment by lalexgap** [comment]
Here's a log file of the issue that I was able to reproduce on this [branch](https://github.com/statechannels/go-nitro/tree/ag/repro-flicker)

[test_direct_defund_flicker.txt](https://github.com/statechannels/go-nitro/files/8643028/test_direct_defund_flicker.txt)

**Comment by lalexgap** [comment]
I think @kerzhner actually discovered this way back with https://github.com/statechannels/go-nitro/issues/314
