### ISSUE TITLE
Publish v0.0.1

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#609]
At some appropriate time we should pin an initial version for go-nitro.

- semver applies per its regular usage
- versioning is managed by git tags:
    - on some acceptable commit of main, run `git tag v0.0.1`, `git push origin v0.0.1` for our init version
    - visit [pkg.go.dev/statechannels/go-nitro](http://pkg.go.dev/statechannels/go-nitro) to ensure that it has picked up the tagged version
- the **special rules** I had remembered concerned major version bumps from `n>1` → `n+1`. (IE, this rule does not apply to the `0.x.y` → `1.0.0` major bump):
    - for these later version bumps, the declared module name in `go.mod` must match the major version number in a specific fashion: `[module github.com/statechannels/go-nitro/v2](http://github.com/statechannels/go-nitro/v2)` for versions v2.x.y, `.../v3` for versions v3.x.y, etc.
    - this rule exists more or less to add friction to the upgrade path across major versions bumps, so that module consumers do not accidentally / automatically pull down breaking changes.

**Comment by geoknee** [comment]
Similar to #390.
