### ISSUE TITLE
The follower may never sign a proposal causing the protocol to stall

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#637]
**Note**: This is based on the code in #618 

Based on the CI logs [here](https://github.com/statechannels/go-nitro/runs/6280716994?check_suite_focus=true)
```
0xBBB676: 21:23:24.769546 engine.go:143: Handling inbound message {To:0xBBB676f9cFF8D242e9eaC39D063848807d3D1D94 Proposals:[{ObjectiveId:VirtualDefund-0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e LedgerId:0x6fb64ca9a3cf319447e2358e1a5428ca32f181bc57af240f35a05ff303f8e620 Target:0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e Type:RemoveProposal TurnNum:4} {ObjectiveId:VirtualDefund-0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0 LedgerId:0x6fb64ca9a3cf319447e2358e1a5428ca32f181bc57af240f35a05ff303f8e620 Target:0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0 Type:RemoveProposal TurnNum:5}] States:[]}
0xBBB676: 21:23:24.769555 engine.go:177: handling proposal {ObjectiveId:VirtualDefund-0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e LedgerId:0x6fb64ca9a3cf319447e2358e1a5428ca32f181bc57af240f35a05ff303f8e620 Target:0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e Type:RemoveProposal TurnNum:4}
0xBBB676: 21:23:24.769987 engine.go:338: Objective VirtualDefund-0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e is WaitingForCompleteFinal
0xBBB676: 21:23:24.769996 engine.go:177: handling proposal {ObjectiveId:VirtualDefund-0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0 LedgerId:0x6fb64ca9a3cf319447e2358e1a5428ca32f181bc57af240f35a05ff303f8e620 Target:0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0 Type:RemoveProposal TurnNum:5}
0xBBB676: 21:23:24.770510 engine.go:338: Objective VirtualDefund-0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0 is WaitingForCompleteLedgerDefunding
```

Bob receives a message with two proposals `VirtualDefund-0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e ` and `VirtualDefund-0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0`.

The objective(VirtualDefund-0x5249f48be7ca2f9a25d054c33b8af5f10d9f36d627a661633561f4b4a56a101e) for the first proposal is still waiting for a signed final state so nothing happens.

The second signed proposal is not the next proposal in the queue so it gets [ignored](https://github.com/statechannels/go-nitro/blob/881eb180e18d5cb3799e999071d30f455f92e5ad/protocols/virtualdefund/virtualdefund.go#L394).

This means that Bob never ends up signing and sending out the proposal for VirtualDefund-0x39e7002e29cd31f7fc4b79ce257948883e2d9e6503e66a9db2e14811dfe631d0

**Comment by lalexgap** [comment]
Lets's say we have two virtual channels V1 and V2 and two virtual defund objective VDF1, VDF2. Both funded by the same ledger channels.

- Alice sends out signed final state for V1 in MSG1
- Alice sends out signed final state for V2 in MSG2
- Bob receives MSG1 and responds with his signed final state for V1 in MSG3
- Bob receives MSG2 and responds with his signed final state for V2 in MSG4
- Irene receives MSG1 and responds with her signed final state for V1 in MSG5
- Irene receives MSG2 and responds with her signed final state for V2 in MSG6
- Bob receives MSG6 from Irene. Bob now has fully signed final state for V2.
- **Important** MSG5 to Bob gets delayed.
- Irene receives MSG3. She now has a fully signed final state for V1.She  sends on a proposal P1 (to defund V1) to Bob in MSG7
- Irene receives MSG4. She now has a fully signed final state for V2. She sends out proposals P1(to defund V1),P2(to defund V2)  to Bob in MSG8. (Note: We send out all unaccepted proposals for a ledger).
- Bob receives MSG7 that includes P1. Since Bob hasn't gotten a fully signed state for V1 he does nothing.
- Bob receives MSG8 that includes proposals P1 and P2. Since Bob is still waiting on a final state he does not send out any messages.
- Bob receives MSG5. Now that he has a signed state for V1 he accepts and sends out P1.

Bob will never end up signing and sending P2. That's because we never receive another message that would trigger a crank of VDF2.

**Comment by lalexgap** [comment]
The message delay virtual funding integration test flickered on [main](https://github.com/statechannels/go-nitro/actions/runs/2271530764/attempts/1). We should investigate and see if this is the root cause of that.

**Comment by kerzhner** [comment]
The setup seems to be:
- Two (or more) virtual channels V and V' supported by the same ledger channel L.
- Concurrent funding and/or defunding objectives for V and V'.

The leader of the channel (Irene in the comment above) arrives at the terminal state for V and V' independent of the follower (Bob in the comment above). The consequence is that the order of the leader's updates to L (aka proposals) can mismatch the order of the follower's updates.

**Comment by kerzhner** [comment]
One thought experiment: when the leader sends a ledger proposal, the leader (by definition) has the supported state for the virtual channel (associated with the proposal). If the leader includes all signatures for the virtual channel, the follower can always sign-off on the proposal.

**Comment by lalexgap** [comment]
> One thought experiment: when the leader sends a ledger proposal, the leader (by definition) has the supported state for the virtual channel (associated with the proposal). If the leader includes all signatures for the virtual channel, the follower can always sign-off on the proposal.

I think this principle should work! However it may require some significant refactoring to implement?

Right now a leader in  a virtual objective will send out the whole [proposal queue](https://github.com/statechannels/go-nitro/blob/ag/retry-objectives/protocols/virtualdefund/virtualdefund.go#L389:L389) when cranking an objective. The proposal queue can contain proposals for other objectives outside the scope of the one we're cranking. Right now that's fine because a `SignedProposal` contains all the information to generate a message , so we can easily generate a `SignedProposal` message for an objective that is not our own.

However if we want to include the supported state for the virtual channel with every proposal we would need to find the virtual channel for every `proposal` in the `ProposalQueue`. This means that the current objective we're cranking would need to know the virtual channel states for other objectives if wanted to included the supported state for every message it's sending out. However the `crank` function doesn't have access to the `store` or a way of finding virtual channels for other objectives.
