### ISSUE TITLE
Virtual defund will call signNextProposal even if our proposal isn't next

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#639]
The follower will call signNextProposal if the [proposal queue contains the proposal we want](https://github.com/statechannels/go-nitro/blob/b426f009f463c5e62333a9b5772e3ab53248d340/protocols/virtualdefund/virtualdefund.go#L287). However the **next** proposal might not be one we're interested in.

Like virtual funding we should only sign the next proposal if the next proposal is for our objective.

**Comment by geoknee** [comment]
Here's the mismatch:
