### ISSUE TITLE
Replace `TrivialApp` with other DApp in gas benchmarks

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#683]
> Previously, we could skip the application check altogether by having all participants countersign the same state.
>
> But now, we must check the application. Hence there is a call to a contract, which previously did not need to be deployed, but now needs to be.
>
> For now we will use the TrivialApp. Longer term we would want to use non trivial apps depending on the channel type.
>
> We use some tricks to predict the contract address, since we need to know this before the test runner starts.
>
> This means that the gas benchmarks can now at least run. The number still need updating, and we should file some issues to return and replace the trivial app with something non trivial.

_Originally posted by @geoknee  in #679_

**Comment by geoknee** [comment]
We could use the newly introduced `ConsensusApp` #754 .

**Comment by geoknee** [comment]
Via #831
