### ISSUE TITLE
The message service should buffer more messages

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#704]
Right now a message service is using a relatively[small buffered channel](https://github.com/statechannels/go-nitro/blob/220ef0ef8418380c74aa9fc12530dc85f2332621/client/engine/messageservice/simple-tcp/simpletcp-messageservice.go#L38) for in and out. 

With such small buffers it's easy for them to get filled up which means the message service or engine can get blocked on writing to these channels. I think we can even run into a deadlock situation.

Using a larger buffered channel for `in` and `out` helps address this but it seems like a code smell to just increase it. Should the message service be doing it's own buffering somehow?

**Comment by geoknee** [comment]
An alternative is to fix #697 and then this problem goes away.

**Comment by lalexgap** [comment]
I think is resolved by #723
