### ISSUE TITLE
Incorporate EthChainService into integration tests

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#714]
Shall we make an issue to track the long-term aims with this? I am thinking the aim should be to drop this into our `client_test` integration tests, and have those tests pass?

_Originally posted by @geoknee in https://github.com/statechannels/go-nitro/pull/709#pullrequestreview-984819236_

**Comment by geoknee** [comment]
@kerzhner should we close this or update it with the current progress?
