### ISSUE TITLE
EthChainService does not implement ChainService API

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#719]
In #710, we added a "return chan" to the `protocols.ChainTransaction` type on the EthChainService's `in` chan. This is to allow consumers to block until the transaction has been submitted (for example, so that they can trigger a block to be mined in a geth simulated backend in a test).

The existing `ChainService` interface was not yet updated, which prevents us from being able to tackle #714 until we resolve the difference.

It seems good to either allow for such a "return chan" in the type specified in the `ChainService` interface -- or else turn transaction submission into a completely synchronous function call (i.e. to not use go channels at all). The former option is a bit more flexible because it allows for _either_ "fire and forget" as well as "block until done" behaviour.

**Comment by kerzhner** [comment]
@geoknee Do you think this has been resolved, or does it still need to be addressed?

**Comment by geoknee** [comment]
I think this is resolved via #723.
