### ISSUE TITLE
Figure out why message size (from proposer in a given ledger channel) seems to monotonically increase over time

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#724]
See https://github.com/statechannels/go-nitro-test-plan/issues/1

**Comment by lalexgap** [comment]
I ran a 5 minute test with 4 hubs, 2 payers, and 2 payees and didn't see message size continue to grow.
[Dashboard link](http://34.168.92.245:3000/d/miulKz7Vk/message-stats?orgId=1&from=1663180753937&to=1663181653937)

![image](https://user-images.githubusercontent.com/1620336/190239512-5296b808-f9c9-4782-89d8-0fdadc916942.png)

**Comment by geoknee** [comment]
I agree that the we don't seem to see the issue in those test runs. I would like to run one more kind of test to be sure:
```
1 hub, 1 payee, n payers
```
With `n` as many as possible (maybe just 10 for starters). If that one goes off without a hitch, I think we can close the issue. 

(I tried running this myself on the VM but ran into issues).

**Comment by lalexgap** [comment]
> I agree that the we don't seem to see the issue in those test runs. I would like to run one more kind of test to be sure:
> 
> ```
> 1 hub, 1 payee, n payers
> ```
> 
> With `n` as many as possible (maybe just 10 for starters). If that one goes off without a hitch, I think we can close the issue.
> 
> (I tried running this myself on the VM but ran into issues).

I'm glad you asked about this one! It looks like the test [deadlocks](http://34.168.92.245:8042/logs?task_id=cchr9n0nr2gm6qosn8sg)  at the end attempting to close the ledger channels, even for very short runs. Messages can also get quite **big**! ([Dashboard link](http://34.168.92.245:3000/d/miulKz7Vk/message-stats?orgId=1&from=1663284704675&to=1663284963589&var-runId=cchrbvgnr2gm6qosn8t0&var-jobCount=25&var-testDuration=2m0s&var-hubs=1&var-payees=1&var-jitter=0&var-latency=0&var-payers=4&var-payeepayers=0))

![image](https://user-images.githubusercontent.com/1620336/190526710-e27d637a-c753-453c-b9da-3cb2915b8f4f.png)

**Comment by geoknee** [comment]
I think it was good to get these results. As I expected, it really stresses out the ledger update protocol, with one ledger channel in particular getting a lot of traffic. 

That said, we don't see the monotonic increase of message size / proposal count. 

Clearly something is going awry at the end there, but it looks to be a separate problem. Therefore I think we can close this.

**Comment by lalexgap** [comment]
For completion sake here's the `1 hub, 1 payee, n payers` scenario now that things are working.
![image](https://user-images.githubusercontent.com/1620336/191607533-50366d87-1408-42c3-b7ef-93c846b1882b.png)

>Therefore I think we can close this.
Agreed!
