### ISSUE TITLE
Fix dependencies relations, use pure `npm ci` without --legacy-peer-deps

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#752]
Use pure `npm ci` without --legacy-peer-deps, which was introduces in #751 as workaround peer-deps issue. More on that [in the 
#751 description](https://github.com/statechannels/go-nitro/pull/751#issue-1276927033).

**Comment by bitwiseguy** [comment]
@geoknee can we close this issue now that we are using `yarn` for all `packages/*`?

**Comment by geoknee** [comment]
Yes
