### ISSUE TITLE
Add a minimal payment API to the go-nitro client

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#772]
See [this design doc.](https://www.notion.so/pl-strflt/Open-Grant-Proposal-go-nitro-Productization-f2b935ab26324545ac6f06f1974a518e#558bb00ca1c44a2795ec51ed421a5081).

Depends on https://github.com/statechannels/go-nitro/issues/793

**Comment by lalexgap** [comment]
Based on discussion with @geoknee we're going to expose the payment API via the client's existing API. The payment API is relatively lightweight and tacking it on to the client API is the quickest way to get payments working.
