### ISSUE TITLE
Allow `ShortcuttingTurnTaking` to accept S0 and S1 as pre-, post-fund states

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#784]
Recently, we prefer to think of turnum=0 as the prefund setup state and turnum=1 as the postfund state. A signature by each participant on one of those states counts as a support proof.

*Originally posted by @geoknee in follow-up discussion of [#676 comment](https://github.com/statechannels/go-nitro/pull/676#discussion_r914713674).*

## ❗ Development dropped
`ShortcuttingTurnTaking` signatures order acceptance logic **development is dropped for now** as there is no high demand on such logic, rather `StrictTurnTaking` (each participant sign a state they are a mover for) and `Consensus` (all participants sign one state) are widely used.

## Implementation

One way of implementing this would be to change signatures order acceptance logic from
```
(signerIndices[i] + nParticipants - shift) % nParticipants <= (turnNum - shift) % nParticipants

```
to
```
(signerIndices[i] + nParticipants - shift) % nParticipants <= (turnNum + nParticipants - shift) % nParticipants,
```
to prevent an underflow discussed [in the comment to #676](https://github.com/statechannels/go-nitro/pull/676#discussion_r914713674).

The requirement
```
largestTurnNum + 1 >= nParticipants
```
should be made avoidable by introducing a new condition to recognize S0 and S1 as pre-, post-fund states:
```
if (largestTurnNum + 1 >= nParticipants && signedVariableParts.length == 1)
```

Summarizing, `ShortcuttingTurnTaking` will be able to accept the following signature orders:
- S0-S(N-1)  as pre-fund states, S_N - S_(2N-1) as post-fund states, S_2N - ... as regular turn taking
- S0 and S1 as consensus pre-, post-fund states, S_2N - ... as regular turn taking

**Comment by geoknee** [comment]
Closing for now, as this is a `wontfix`.
