### ISSUE TITLE
`challenge_test.go` should test setup turn numbers.

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#785]
In the past this test tried to construct a support proof using unanimous consensus on a `turnNum=0` state, using the `ConsensusApp`. 

Due to rapid changes around the on chain code, for a time we will not support such a support proof. In the near term we will restore this behaviour.

Therefore the test uses a different turn number temporarily. This issue tracks the TODO to reinstate the original test (and/or include more turn numbers in the test).

**Comment by nksazonov** [comment]
I believe by merging #834 this issue can be tackled now.
