### ISSUE TITLE
Create Payment/Receipt managers once virtual channels are opened.

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#794]
We need to register virtual channels when they're open and able to be used.

One thing we may want to be careful about is receiving messages out of order. For example what if the first voucher arrives before the last signature on the post fund setup?

**Comment by geoknee** [comment]
@lalexgap can we close this or is there more work to be done?

**Comment by lalexgap** [comment]
> @lalexgap can we close this or is there more work to be done?

This can be closed!
