### ISSUE TITLE
Add the ability to settle vouchers and close the virtual channel

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/go-nitro#795]
We will need to change the `virtualdefund` objective so that:
    
1. Alice & Bob agree on the “largest voucher”
1. Considering that a voucher might be in-flight, maybe Bob would expect Alice to provide the largest voucher within the objective’s business logic, and we program Alice to politely send the largest voucher (even though she’s not obligated to).
2. Once Bob receives the largest voucher, he constructs and signs a final state, and sends to Irene
3. Once Irene has a final state signed by Bob, she signs it and sends to Alice & Bob
4. Once everyone has a supported final state, they remove the guarantees from their ledger channels

There are two options for orchestrating the virtual channel to close:

A. Alice, Bob & Irene sign “forcing states” that are not final, but include the information necessary to construct the final state. This is compatible with the current message format
B. Bob & Irene send messages to Alice saying something like “Alice, I’d like to close the virtual channel. Please provide the largest voucher to Bob.” This is not compatible with the current message format.

**Question:** If we choose B, should objectives be responsible for interpreting their own payloads? If so, would there be some concern about spreading out message-related responsibilities? duplicated code?

**Comment by lalexgap** [comment]
Since we've decided to include vouchers in the message format (see #824) I think approach B would make sense.

**Comment by lalexgap** [comment]
See the [ADR](https://github.com/statechannels/go-nitro/pull/863) for the approach we will follow.

**Comment by lalexgap** [comment]
This was fixed by #866
