### ISSUE TITLE
publish on pkg.go.dev

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#80]
When the time is right!

**Comment by NiloCK** [comment]
This seems to be done: https://pkg.go.dev/github.com/statechannels/go-nitro

Was this publication intentional?

**Comment by geoknee** [comment]
Let's repurpose this issue to: come up with  (and _document_) a strategy for publishing new versions of `go-nitro`.

**Comment by geoknee** [comment]
The original aim of the issue is built on a slight misunderstanding of what `pkg.go.dev` is. It is not a repository for modules, it is merely an index. Our code is published again each time we push to github, which is where the code is distributed from. `pkg.go.dev` merely indexes go modules (hosted in many different places). It was only a matter of time before it got wind of `go-nitro` :-) 

We still need to think about publishing _tagged_ versions, which is done by pushing a tagged commit to github. We should use semantic versioning -- so should be thinking about whether the changes we make are patches / features / breaking etc.
