### ISSUE TITLE
BUG: no `isFinal` check during conclude. 

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#813]
The [_conclude  function in ForceMove](https://github.com/statechannels/go-nitro/blob/d9bc78c4aeceb7fa221d657f8be1d0f5e5a29ef2/nitro-protocol/contracts/ForceMove.sol#L133) specifies in the docstring that all of the provided states in the support proof must be final (which makes perfect sense) but there are no checks to enforce this?

---
originally posted by @willemolding in slack

**Comment by geoknee** [comment]
It used to be that the state hashes were constructed to have isFinal=true when doing signature recovery, so the check was there implicitly. But this has apparently been lost in recent refactoring! I will make an issue to fix this and protect with a regression test.

**Comment by willemolding** [comment]
I think the [docstring comment](https://github.com/statechannels/go-nitro/blob/d9bc78c4aeceb7fa221d657f8be1d0f5e5a29ef2/nitro-protocol/contracts/ForceMove.sol#L131) might be incorrect as well. Only the highest supported state needs to have `isFinal=true` right?

**Comment by geoknee** [comment]
Actually, there should be a signature from each and every participant on the same `isFinal` state. The point of `conclude` is that there will be no window of time to dispute the channel: so we require unanimous consensus on the state, _and_ the fact that it is final.

**Comment by willemolding** [comment]
Would it not have the same requirements as `checkpoint`? In that case you could also provide a proof comprised of multiple states with valid transitions and in this case only the last one would need to be final. Or am I missing something here?

**Comment by geoknee** [comment]
It might well be possible to combine `checkpoint` and `conclude`, that's an interesting suggestion. The ultimate behaviour / consequences of the two methods is very different though, so there may be some value in keeping them separate. They key thing about `conclude` is that there is no time period allowed for counter-challenges or checkpoints. The channel will finalize **immediately*.*

For this reason, e don't want to allow "the dispute time window to be skipped" in the case you mention: where a support proof has been provided and **only ** the candidate state has `isFinal=true`. 

Imagine we are playing chess: I could take one of your early moves, and sign a "private" update (transitioning legally from your move) with "isFinal=true" and not broadcast it. I then continue to play the game in a different branch, but keep this private state as an insurance policy. If you start to dominate the game, I can now force my (much more favourable to me) private state update on chain and **you wouldn't have a chance to respond**. 

If we require all participants to have signed the `isFinal=true` state, (we call this a "finalization proof")  we get around this problem. As soon as any participant makes such as a signature, they immediately stop signing updates in that channel, because it is not safe to do so -- the mechanism to allow newer states to overwrite old states on chain has been bypassed.

**Comment by willemolding** [comment]
> Imagine we are playing chess: I could take one of your early moves, and sign a "private" update (transitioning legally from your move) with "isFinal=true" and not broadcast it

I think in this case the state update is not legal according to the rules of the game. The game logic has access to the whole `variablePart` and should enforce that setting `isFinal` to true without a checkmate is invalid. If both players want to conclude the game early though they could sign a finalization proof regardless of the state and since it is only a single state the transition check would not be applied.

**Comment by geoknee** [comment]
I see what you're saying. I think we've adopted a slightly different approach in the past, where `isFinal`, finalization proofs, and `conclude` are all entirely escaped from application logic. That is to say, concluding is treated as a special case in the core protocol (and doesn't depend on any application rules at all).

Having the ability to _unilaterally_ transition to a final state (if allowed by the rules) does confer some benefits. It can save time and cryptographic operations, particularly welcome and easy-to-reason through for something like a unidirectional payment channel (payer has no risk from payee submitting stale state). 

We should consider the tradeoffs as we migrate to our v2 implementation. As we do that, we are tending to give more responsibility to application developers. The behaviour above is leaning into this trend even more (now they need to worry about `isFinal`). This carries a risk and makes it more difficult for generic off-chain software to make inferences about states without understanding each application. 

Here are some options: 
1. `conclude` could **only** accept a single, fully countersigned `isFinal` state and not do any further support checks. 
2. We could modify the current implementation to check **only** the supported state for the `isFinal` condition. And update the docstring (and generally signal how this works clearly in the docs). I think this is essentially what you are proposing.

#814 doesn't quite do 1, so I would suggest we drag it in that direction for now, and then continue to consider 2 as an optimisation.

**Comment by nksazonov** [comment]
It is also worth mentioning, that (1) with participants imprudence can lead to application-incorrect moves.

Imagine an application, which make some checks when provided states with `isFinal = true`. If `conclude` does not do any further support checks, except that state is fully countersigned `isFinal`, then participants can supply `isFinal` state, which will pass `conclude` checks, but will be incorrect by application logic means. Thus, `conclude` call that should be reverted, will succeed.

On the other hand, if by not calling application in `conclude` when fully countersigned `isFinal` state is submitted, we want to add a safety backdoor from any state channel application, there is no other way than this.

Therefore, logic changes to `conclude` should depend on whether we just want to simplify this method for participants or add a safety backdoor exit from any state channel.

**Comment by willemolding** [comment]
There is surely a pretty good argument for having the ability to exit regardless of application rules. Applications, especially reasonably complex games, are going to have bugs and having the ability for both parties to collaborate and exit is a nice way to reduce the risk.

**Comment by nksazonov** [comment]
> That is to say, concluding is treated as a special case in the core protocol (and doesn't depend on any application rules at all).

@geoknee , could you explain what is backing this decision, please?

**Comment by geoknee** [comment]
> > That is to say, concluding is treated as a special case in the core protocol (and doesn't depend on any application rules at all).
> 
> @geoknee , could you explain what is backing this decision, please?

@nksazonov I think there are a few reasons for this current behaviour:

1 The  "safety backdoor" that you have mentioned and that @willemolding argues for. I tend to agree that this is a nice feature.
2. The original version of nitro was more focussed on the core protocol providing more features and more guarantees. Nitro v2 is moving away from that, towards a world where features and security guarantees are encoded into each application. This allows for greater extensibility and flexibility for applications, and even allows us to convert things like virtual channels into upgradeable / pluggable components by writing them as applications. 

To keep this discussion on track -- I think we all agree that some `isFinal` check is required during `conclude`, and that it is currently missing. So it would be good to focus on fixing that bug in the first instance. We can keep discussing the best solution in parallel to fixing the bug.  

For this reason I believe we should merge #814. I would then work on implementing option 1 above because I believe it is worth retaining the "safety backdoor" as discussed.

**Comment by nksazonov** [comment]
Yes, the bug definitely should be fixed. 
Meanwhile, we could come to the decision on this one (option 1 vs option 2 vs else) not to change the behaviour once again in the future.

What do you think of separating safety backdoor from `conclude` by creating some method (e.g. `exit`), which will resemble option 1, but keep application check in `conclude` to allow applications, which include different checks if state is marked `isFinal`.

**Comment by geoknee** [comment]
> What do you think of separating safety backdoor from `conclude` by creating some method (e.g. `exit`), which will resemble option 1, but keep application check in `conclude` to allow applications, which include different checks if state is marked `isFinal`.

I'm in favour of separating the two approaches, in principle. However I would prefer:

a) preserve nitro v1 behaviour by having a `conclude` method requiring unanimous consensus on an `isFinal` state and skipping the challenge timeout. This gives us the safety backdoor / rapid close of a channel as a core feature which has been tried and tested, and exposes quite a small attack surface.
b) Potentially supporting  the **new**  pattern of allowing the challenge period to be skipped if a support proof for an `isFinal` state is provided, regardless of the signatures in that proof but deferring to the application to make whichever checks it deems appropriate. 

We can then consider b separately as a new feature and give it proper scrutiny. Right now it seems to me to add a lot of attack surface / possibility for critical bugs. For example, I think it would introduce a vulnerability into literally all of our existing `IForceMoveApps`! Furthermore, there don't seem to be so many applications which might make use of b), other than the unidirectional payments (admittedly this may be a widely used `IForceMoveApp`). Personally, I feel that the tradeoff is not worth it.

**Comment by nksazonov** [comment]
> We can then consider b separately as a new feature and give it proper scrutiny. Right now it seems to me to add a lot of attack surface / possibility for critical bugs. For example, I think it would introduce a vulnerability into literally all of our existing IForceMoveApps! Furthermore, there don't seem to be so many applications which might make use of b), other than the unidirectional payments (admittedly this may be a widely used IForceMoveApp). Personally, I feel that the tradeoff is not worth it.

I agree with you. To continue development process, let's merge #814 and keep our minds open if any DApp with b) logic appears.
