### ISSUE TITLE
`golanglint-ci` does not start properly 

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#819]
See this run https://github.com/statechannels/go-nitro/runs/7840888001?check_suite_focus=true. 

This issue seems related:
https://github.com/golangci/golangci-lint/issues/2374

**Comment by lalexgap** [comment]
I think our CI is using go 1.19 since we're using `go-version: "^1.18.0"`. However golanglint-ci only added support for go1.19 in `1.48.0`.

I think the two options are:
- Upgrade to go1.19
- Do not specify a version range and just using `1.18.0`
