### ISSUE TITLE
Allow protocols to implement their own message format

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#860]
To integrate voucher payments into virtual defunding we'll need to tweak the message format. Instead of having one message format that all the protocols must implement we should look at allowing protocols to implement their own message format.

**Comment by geoknee** [comment]
Discussed in standup today:

From the POV of a protocol designer.

Be awesome for each protocol do be able to enumerate the message payload types that it supports. Then:

* It is easy to add a new message payload to a protocol, and have total control of what kind of data is on that payload
* It is easy to enumerate all message types in the entire system, simply list each message payload type for each protocol

We can keep the engine ignorant of these details by having it pass around serialized payloads, which then get deserialized into concrete types by each protocol. The protocols then serialize the payloads before returning them inside a message as a  side effect.

**Comment by lalexgap** [comment]
This was fixed by #864
