### ISSUE TITLE
Consider: add contract address to FixedPart

### ISSUE THREAD

**Issue by NiloCK** [statechannels/go-nitro#889]
During Standup 2022-09-21, we discussed tooling for redeploying `NitroAdjudicator` on the existing hardhat docker instance used by our testground tests. A considered option was **redeploying new adjudicator builds to the existing long-running testnet**. This led to the question of whether there are real-world potentials for chains with multiple nitroadjudicators running simultaneously. It's not completely obvious that persons would benefit from this, but it *is* obvious that there's no way to prevent it.

Existing `FixedPart` stuct contains `ChainID` in order to prevent replay attacks. This should probably be extended to also include `AdjudicatorAddress`, so that signatures can't be replayed against different networks living on the same chain.

Optionally, the adjudicator address and chain ID could be collapsed into a single deterministic value called something like `networkID := hash(chainID + adjudicatorAddress)`

```
// solidity
struct FixedPart {
    uint256 chainId;
    address adjudicator; // add this
    address[] participants;
    uint48 channelNonce;
    address appDefinition;
    uint48 challengeDuration;
}

// go
FixedPart struct {
 ChainId           *types.Uint256
 Adjudicator       types.Address // add this
 Participants      []types.Address
 ChannelNonce      *types.Uint256 // uint48 in solidity
 AppDefinition     types.Address
 ChallengeDuration *types.Uint256
}
```

**Comment by geoknee** [comment]
My preference would be to just add it into the FixedPart at the top level. And to avoid `networkID`, as I think that already has a meaning on Ethereum.
