### ISSUE TITLE
Single pathway for contract compilation

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro#911]
From @geoknee: we have two compilation pathways in the repo. One via hardhat, and the other via solc directly (which produces the bytecode above). The two pathways are generally configured slightly differently (optimization runs, etc).

The two pathways should be collapsed into a single, canonical pathway.

**Comment by geoknee** [comment]
I think it is possible to not generate bytecode (or not save it, at least) when we call out to `solc` and then `abigen`. It might break a couple of things but this would prevent us from having two sources of truth about bytecode in the repo?
