### ISSUE TITLE
Add a polling mechanism for contract state

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#944]
Since the FEVM is not going to be supporting events in the short term, we need a workaround for listening to "deposit" events. 

We can do this by polling the `holdings()` getter on the adjudicator. 

The work can happen in a separate feature branch for now, since it will be somewhat hacky. 

The long term goal is to have deposits "detected" by an fevm chain service written in Go. To get there, we will likely need to lean on this issue, as well as some work from @kerzhner on targeting state-modifying methods on FEVM, also potentially this work #923.

**Comment by lalexgap** [comment]
Closed by #993
