### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#948]
Some of the information is out of date / broken.

I think the time is right to change the emphasis of the readme, from targetting contributors to targetting consumers. 

The architecture diagram can be moved to another file. We should focus on the API, the existing features and the planned features. 

We should tidy up "work in progress" and "v2" statements.

**Comment by NiloCK** [comment]
- the architecture diagram exists also in the `/client/readme.md`
- contributor specific readme info could be pushed toward `contributing.md`
- As far as I can tell, there's no in-repo documentation on building / previewing the docs website.
