### ISSUE TITLE
Implement a durable store

### ISSUE THREAD

**Issue by lalexgap** [statechannels/go-nitro#984]
Currently we are using a in-memory store to store all our data, meaning clients cannot survive being restarted.

We should investigate and implement some kind of storage solution that allows us to persist data in a more permanent manner. 

We probably want something relatively light-weight and low configuration for now. Maybe a local SQL db?

**Comment by geoknee** [comment]
Another benefit will be debugging. If we can access client's stores after a failed test run, we can check the date in their stores.
