### ISSUE TITLE
Test flicker "error in tun loop, objective not approved"

### ISSUE THREAD

**Issue by geoknee** [statechannels/go-nitro#991]
This seems pretty rare, but I saw it on a recent unrelated PR 

```
panic: 0xBBB676f9cFF8D242e9eaC39D063848807d3D1D94, error in run loop: objective not approved 
```

https://github.com/statechannels/go-nitro/actions/runs/3478682096/jobs/5816332274

**Comment by lalexgap** [comment]
@geoknee this is pretty old now, do you think we can close it?

**Comment by geoknee** [comment]
Yes let's close until (if) it pops up again.
