### ISSUE TITLE
Allow overriding `NitroAdjudicator` functions

### ISSUE THREAD

**Issue by nksazonov** [statechannels/go-nitro#994]
## Problem

At Yellow we want to make our own `YellowAdjudicator`, which adds some logic to main adjudication methods (set not fully defined yet). However, that does not seem possible right now, as these methods are declared `external`, which means we can't invoke them in the inherited contract.

## Solution 1

The simplest and the most flexible solution would be to declare those methods `virtual` so that we can override them in our own Adjudicator.

## Solution 2

Another solution is to add hooks (`beforeDeposit`, `afterDeposit`, etc.) to each method we would like to add some behaviour to. Nevertheless, this looks not as flexible as the other solution, because it requires `NitroAdjudicator` to define those hooks and inheriting adjudicator to override them anyway. The only strong (and dubious) point of this solution seems to be the insurance the base `NitroAdjudicator` method is called and not forgotten.

**Comment by nksazonov** [comment]
@geoknee , what do you think of this?

**Comment by geoknee** [comment]
@nksazonov I think Solution 1 seems very reasonable. Will this require changes to `ForceMove` and `MultiAssetHolder`, as well as `NitroAdjudicator`?

**Comment by nksazonov** [comment]
> @nksazonov I think Solution 1 seems very reasonable. Will this require changes to `ForceMove` and `MultiAssetHolder`, as well as `NitroAdjudicator`?

Actually, I think so. 

Here are all `public`/`external` methods, which may be interesting to override:
- `MultiAssetHolder`:
   - `deposit`
- `ForceMove`:
   - `challenge`
   - `checkpoint`
   - `conclude`
- `NitroAdjudicator`:
   - `concludeAndTransferAllAssets`
   - `transferAllAssets`
   
I think making these methods virtual will provide any logic modification in the derived contract.
